---
permalink: sg6000/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: SG6000 アプライアンスでメンテナンス手順を実行する必要がある場合があります。このセクションの手順は、アプライアンスが StorageGRID システムにストレージノードとしてすでに導入されていることを前提としています。 
---
= SG6000アプライアンスのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG6000 アプライアンスでメンテナンス手順を実行する必要がある場合があります。

このセクションでは、SG6000アプライアンスのメンテナンスに固有の手順について説明します。アプライアンスがStorageGRID システムにストレージノードとしてすでに導入されていることを前提としています。

を参照してください link:../commonhardware/index.html["一般的な手順"] すべてのアプライアンスで使用するメンテナンス手順。

を参照してください link:../installconfig/configuring-hardware.html["ハードウェアをセットアップする"] アプライアンスの初期インストールおよび設定時にも実行されるメンテナンス手順。

サービスの中断を回避するには、アプライアンスをシャットダウンする前に他のすべてのストレージノードがグリッドに接続されていることを確認するか、サービスの停止期間が許容範囲内であれば、スケジュールされたメンテナンス期間中にアプライアンスをシャットダウンします。の情報を参照してください https://docs.netapp.com/us-en/storagegrid-118/monitor/monitoring-system-health.html#monitor-node-connection-states["ノードの接続状態を監視しています"^]。


CAUTION: オブジェクトのコピーを 1 つだけ作成する ILM ルールを使用したことがある場合は、スケジュールされたメンテナンス時間中にアプライアンスをシャットダウンする必要があります。そうしないと、ストレージノードのサービスを停止するメンテナンス手順 の実行中に、これらのオブジェクトへのアクセスが一時的に失われる可能性があります。の情報を参照してください https://docs.netapp.com/us-en/storagegrid-118/ilm/index.html["情報ライフサイクル管理によるオブジェクトの管理"^]。
