---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: SG6000-CNコントローラが適切に機能しない場合や障害が発生した場合は、交換が必要になることがあります。 
---
= SG6000-CN コントローラを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG6000-CNコントローラが適切に機能しない場合や障害が発生した場合は、交換が必要になることがあります。

.作業を開始する前に
* 交換するコントローラと同じパーツ番号の交換用コントローラを用意しておきます。
* コントローラに接続する各ケーブルを識別するためのラベルを用意しておきます。
* データセンター内で交換するコントローラの物理的な場所を確認しておきます。
+
link:locating-controller-in-data-center.html["データセンターでコントローラを探します"]



.このタスクについて
SG6000-CN コントローラを交換すると、アプライアンスストレージノードにアクセスできなくなります。SG6000-CN コントローラが十分に機能している場合は、この手順 の開始時に通常の方法でシャットダウンを実行できます。


NOTE: StorageGRID ソフトウェアをインストールする前にコントローラを交換すると、この手順 の完了後すぐに StorageGRID アプライアンスインストーラにアクセスできない場合があります。StorageGRID アプライアンスインストーラには、アプライアンスと同じサブネット上の他のホストからはアクセスできますが、他のサブネット上のホストからはアクセスできません。この状態は 15 分以内に（元のコントローラのいずれかの ARP キャッシュエントリがタイムアウトした時点で）自動的に解消されます。あるいは、古い ARP キャッシュエントリをローカルルータまたはゲートウェイから手動でパージすれば、すぐにこの状態を解消できます。

.手順
. アプライアンスの現在の設定を表示して記録します。
+
.. 交換するアプライアンスにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



.. 入力するコマンド `*run-host-command ipmitool lan print*` をクリックして、アプライアンスの現在のBMC設定を表示します。


. SG6000-CNコントローラが動作していて通常の方法でシャットダウンできる場合は、 link:power-sg6000-cn-controller-off-on.html#shut-down-sg6000-cn-controller["SG6000-CNコントローラをシャットダウンします"]。
. このStorageGRID アプライアンスのいずれかのネットワークインターフェイスがDHCP用に設定されている場合は、交換用アプライアンスのMACアドレスを参照するために、DHCPサーバの永続的なDHCPリース割り当てを更新する必要があります。この更新により、アプライアンスに想定されるIPアドレスが割り当てられます。を参照してください link:../commonhardware/locate-mac-address.html["MACアドレス参照を更新します"]。
. SG6000-CN コントローラを取り外して交換します。
+
.. ケーブルにラベルを付けてから、ケーブルと SFP+ または SFP28 トランシーバを取り外します。
+

NOTE: パフォーマンスの低下を防ぐため、ケーブルをねじったり、折り曲げたり、挟んだり、踏んだりしないでください。

.. 障害が発生したコントローラをキャビネットまたはラックから取り外します。
.. 交換用コントローラをキャビネットまたはラックに取り付けます。
.. ケーブルと SFP+ または SFP28 トランシーバを交換します。
.. コントローラと link:../installconfig/viewing-status-indicators.html["コントローラのLEDを監視する"] および link:../installconfig/troubleshooting-hardware-installation.html#view-boot-codes["ブート時のコード"]。
+
コントローラの起動時に、コントローラおよびアプライアンスコンポーネントの保留中の更新が自動的にインストールされます。これらの更新のインストールが完了するまでに1時間以上かかることがあり、コントローラが何度もリブートすることがあります。

+

CAUTION: ファームウェアの更新中にアプライアンスが_not_であることが確実な場合を除き、アプライアンスを手動でリブートしないでください。

+
次を接続できます： link:../installconfig/troubleshooting-hardware-installation.html["モニタ"] または link:../installconfig/accessing-storagegrid-appliance-installer.html["サービスラップトップ"] SG6000-CNコントローラに接続し、更新インストールの進行状況を監視します。

+

NOTE: サービスラップトップ接続は、インストールプロセスの一部の段階では使用できない場合があります。



. コントローラを交換したアプライアンスでキー管理サーバ（KMS）を使用してデータを暗号化していた場合は、ノードをグリッドに追加する前に追加の設定が必要になることがあります。ノードが自動的にグリッドに追加されない場合は、次の設定が新しいコントローラに転送されたことを確認し、想定される設定と異なる設定があれば手動で設定します。
+
** link:../installconfig/configuring-network-links.html["ネットワークリンクを設定する"]
** link:../installconfig/setting-ip-configuration.html["StorageGRID IP アドレスを設定する"]
** https://docs.netapp.com/us-en/storagegrid-118/admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance["アプライアンスのノード暗号化を設定します"^]


. コントローラを交換したアプライアンスにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。


. アプライアンスのBMCネットワーク接続をリストアします。次の 2 つのオプションがあります。
+
** 静的IP、ネットマスク、およびゲートウェイを使用します
** DHCPを使用して、IP、ネットマスク、およびゲートウェイを取得します
+
... 静的IP、ネットマスク、およびゲートウェイを使用するようにBMCの設定をリストアするには、次のコマンドを入力します。
+
`*run-host-command ipmitool lan set 1 ipsrc static*`

+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`

+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`

+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

... DHCPを使用してIP、ネットマスク、およびゲートウェイを取得するようにBMCの設定を復元するには、次のコマンドを入力します。
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`





. BMCネットワーク接続をリストアしたら、BMCインターフェイスに接続して監査し、追加で適用したBMCのカスタム設定をリストアします。たとえば、SNMPトラップの送信先やEメール通知の設定を確認する必要があります。を参照してください link:../installconfig/configuring-bmc-interface.html["BMCインターフェイスの設定"]。
. アプライアンスノードが Grid Manager に表示され、アラートが表示されていないことを確認します。


部品の交換後、障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"^] 詳細については、を参照してください。

.関連情報
link:../installconfig/sg6000-cn-installing-into-cabinet-or-rack.html["SG6000-CNをキャビネットまたはラックに設置します"]

link:../installconfig/viewing-status-indicators.html["ステータスインジケータを表示します"]

link:../installconfig/troubleshooting-hardware-installation.html#view-boot-codes["SG6000-CN コントローラのブート時のコードを確認します"]
