---
sidebar: sidebar 
permalink: whats-new-appliances.html 
keywords: storagegrid, appliance, whats new 
summary: このドキュメントサイトの新機能をご確認ください。 
---
= StorageGRIDアプライアンスの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
StorageGRIDアプライアンスの新機能について説明します。



== SG120およびSG1200サービス アプライアンス

新しい StorageGRID SG120 および SG1200 サービスアプライアンスは、管理機能と負荷分散性能を向上させた、進化的なハードウェアアップデートです。link:./installconfig/hardware-description-sg120-and-1200.html["SG120およびSG1200サービスアプライアンス：概要"]を参照して詳細を確認してください。



== SGF6212 アプライアンス

新しい StorageGRID SGF6212 ストレージアプライアンスは、コンピューティングコントローラとストレージコントローラを 1U シャーシに統合したコンパクトな設計が特徴です。このアプライアンスは、耐障害性の高いオブジェクトストレージを提供する RAID 構成の 12 台の SSD NVMe ドライブをサポートしています。link:installconfig/hardware-description-sg6200.html["SGF6212アプライアンス：概要"]を参照して詳細を確認してください。



== SG6260アプライアンス

新しい StorageGRID SG6260 アプライアンスには、コンピューティング コントローラと、2 つのストレージ コントローラと 60 台のドライブを含むストレージ コントローラ シェルフ、およびキャッシュ用の 2 台の NVMe SSD ドライブが含まれています。オプションで、60 ドライブ拡張シェルフを SG6260 に追加できます。詳細については、link:./installconfig/hardware-description-sg6200.html["SGF6200アプライアンス：概要"]を参照してください。



== クライアントネットワークはIPアドレスなしで構成できます

IP アドレスを指定せずにクライアント ネットワークを有効にできるようになりました。これにより、クライアント ネットワークは、インターフェイス自体に追加の IP アドレスを必要とせずに、 StorageGRIDで VLAN インターフェイスを構成できるようになります。。 link:.//installconfig/setting-ip-configuration.html["StorageGRID IP アドレスを設定する"] 。



== StorageGRIDソフトウェアとアプライアンスインストーラのバージョン番号が一致しました

StorgeGRID バージョン 12.0 では、 StorageGRIDアプライアンス インストーラーのバージョン番号はStorageGRIDソフトウェアのバージョンと一致します。ユーザーは、どのバージョンが連携して動作するかを把握する必要がなくなりました。。 link:./installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["StorageGRID アプライアンスインストーラのバージョンを確認してアップグレードします"] 。



== BMCノシヨウホウ

StorageGRIDアプライアンスのBMCインターフェイスの使用に関する詳細情報が利用可能になりました。。 link:./commonhardware/use-bmc.html["StorageGRIDアプライアンスのベースボード管理コントローラ（BMC）の使用"] 。
