---
permalink: sg100-1000/shut-down-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg1000, SG100, power off, turn off, shut off, shutdown, shut down, 
summary: サービスアプライアンスをシャットダウンして、ハードウェアのメンテナンスを行います。 
---
= SG100またはSG1000のシャットダウン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスアプライアンスをシャットダウンして、ハードウェアのメンテナンスを行います。

.作業を開始する前に
物理的には link:locating-controller-in-data-center.html["サービスアプライアンスの場所"] データセンターのメンテナンスが必要。

.このタスクについて
サービスの中断を回避するには、サービスの中断が許容される時間帯に、スケジュールされたメンテナンス時間内にサービスアプライアンスをシャットダウンします。

.手順
. アプライアンスをシャットダウンします。
+

CAUTION: 次のコマンドを入力して、アプライアンスの制御シャットダウンを実行する必要があります。不要なアラートを回避し、フルログを利用できることを確認し、サービスの停止を回避するために、可能なかぎり通常の方法でシャットダウンすることを推奨します。

+
.. グリッドノードにまだログインしていない場合は、PuTTYまたは別のsshクライアントを使用してログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



.. サービスアプライアンスをシャットダウンします。+
`*shutdown -h now*`
+
このコマンドの実行には 10 分程度かかる場合があります。



. 次のいずれかの方法で、アプライアンスの電源がオフになっていることを確認します。
+
** アプライアンス前面の電源 LED を調べて、消灯していることを確認します。
** BMC インターフェイスの電源制御ページで、アプライアンスがオフになっていることを確認します。



