---
permalink: sg6200/replace-nic-in-sg6200.html 
sidebar: sidebar 
keywords: storagegrid, sg6200, storage node, storage appliance, Replacing, replace, NIC, network interface card 
summary: SGF6212のネットワークインターフェースカード（NIC）が最適に機能していない場合、または故障している場合は、交換する必要があるかもしれません。 
---
= SGF6212またはSG6200-CNの内蔵NICを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SGF6212またはSG6200-CNに内蔵されているNetwork Interface Card（NIC）が最適に機能していない場合、または故障している場合は、交換が必要になる可能性があります。

.このタスクについて
サービスの中断を防ぐために、ネットワークインターフェイスカード（NIC）の交換を開始する前に他のすべてのストレージノードがグリッドに接続されていることを確認するか、サービスの中断が許容される時間帯にスケジュールされたメンテナンス時間内にNICを交換してください。の情報を参照してください https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states["ノードの接続状態を監視しています"^]。


CAUTION: オブジェクトのコピーを1つだけ作成するILMルールを使用したことがある場合は、この手順の実行中はそれらのオブジェクトに一時的にアクセスできなくなる可能性があるため、スケジュールされたメンテナンス時間中にNICを交換する必要があります。についての情報を参照してください https://docs.netapp.com/us-en/storagegrid/ilm/why-you-should-not-use-single-copy-replication.html["シングルコピーレプリケーションを使用しない理由"^]。

.作業を開始する前に
* 正しい交換用NICを用意しておきます。
* link:locating-sg6200-in-data-center.html["SGF6212アプライアンスまたはSG6200-CNコントローラの物理的な場所を確認した"]データセンターでNICを交換します。
+

NOTE: ラックからアプライアンスを取り外す前に、link:power-sg6200-off-on.html#shut-down-the-sgf6212-appliance-or-sg6200-cn-controller["アプライアンスの通常のシャットダウン"]が必要です。

* すべてのケーブルを外し、link:reinstalling-sg6200-cover.html["アプライアンスカバーを取り外した"]。
* 次のことを決定しました。 link:verify-component-to-replace.html["交換するNICの場所"]。
+
本機器に搭載されている3つのNICは、シャーシ内の以下の位置にある3つのライザーアセンブリに収められています（上部カバーを取り外した状態の機器背面図を参照）：

+
image:../media/drw_s2025_io_numbers_ieops-2554.svg["アプライアンス内のNICの場所"]





== ステップ1：NICを取り外す

[role="tabbed-block"]
====
.NIC 1/NIC 2
--
.手順
. ESD リストバンドのストラップの端を手首に巻き付け、静電気の放電を防ぐためにクリップの端をメタルアースに固定します。
. アプライアンスの背面にあるNICを含むライザーアセンブリの場所を確認します。
. 故障したNICが搭載されたライザーの青色のロックラッチを上に回転させて開きます。
+
image:../media/drw_s2025_io_1_2_replace_ieops-2555.svg["ライザーアセンブリからNIC 1またはNIC 2を取り外す"]

. 青色のマークが付いた穴を使って、故障したNICが取り付けられたライザーアセンブリを慎重に上方に持ち上げてください。ライザーアセンブリを持ち上げるときは、シャーシの前方に向かって移動させてください。そうすることで、取り付けられているNICの外部コネクタがシャーシをクリアできるようになります。
. NIC にアクセスするには、ライザーを平らな帯電防止面の上に、金属フレーム側を下にして置いてください。
. 故障したNICの青いラッチを開け、ライザーアセンブリから慎重に取り外してください。NICをコネクタから取り外す際は、NICを少し揺らしてください。過度の力を加えないでください。
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["ライザーアセンブリからIOカードを取り外す"]

. ライザーとNICを平らな帯電防止面に置いてください。


--
.NIC 3
--
.手順
. ESD リストバンドのストラップの端を手首に巻き付け、静電気の放電を防ぐためにクリップの端をメタルアースに固定します。
. 故障したNICが付いているライザーの青いロックを回転させて、開位置にします。
+
image:../media/drw_s2025_io_3_replace_ieops-2556.svg["ライザーアセンブリからNIC 3を取り外す"]

. 青色のマークが付いた穴とライザーの端を使って、ライザーアセンブリを慎重に持ち上げてください。ライザーアセンブリを持ち上げるときは、シャーシの前方に向かって移動させてください。そうすることで、取り付けられているNICの外部コネクタがシャーシをクリアできるようになります。
. NIC にアクセスするには、ライザーを平らな帯電防止面の上に、金属フレーム側を下にして置いてください。
. 故障したNICの青いラッチを開け、ライザーアセンブリから慎重に取り外してください。NICをコネクタから取り外す際は、NICを少し揺らしてください。過度の力を加えないでください。
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["ライザーアセンブリからIOカードを取り外す"]

. ライザーとNICを平らな帯電防止面に置いてください。


--
====


== ステップ2：内蔵NICを再インストールする

取り外したNICと同じ場所に交換用NICを取り付けます。

[role="tabbed-block"]
====
.NIC 1/NIC 2
--
.手順
. ESD リストバンドのストラップの端を手首に巻き付け、静電気の放電を防ぐためにクリップの端をメタルアースに固定します。
. 交換用NICをパッケージから取り出します。
. 交換用NICをライザーアセンブリに取り付けます。
+
.. 青色のラッチが開いた位置にあることを確認します。
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["ライザーアセンブリへのIOカードの取り付け"]

.. NICをライザーアセンブリ上のコネクタに位置合わせします。NICをコネクタに完全に差し込まれるまで慎重に押し込み、その後、青色のラッチを閉じます。


. ライザーアセンブリをシャーシに再取り付けします。
+
.. ライザーアセンブリの位置合わせ穴の位置を確認し、システムボード上のガイドピンと一致させて、ライザーアセンブリが正しく配置されるようにします。
+
image:../media/drw_s2025_io_1_2_reinstall_ieops-2685.svg["ライザーアセンブリ内のNIC 1またはNIC 2の交換"]

.. ライザーアセンブリがシステム基板のコネクタおよびガイドピンに揃うように、ライザーアセンブリをシャーシに配置します。
.. ライザーアセンブリが完全に装着されるまで、青いマークの付いた穴の横にある中心線に沿って慎重に押し込みます。


. アプライアンスで実行する他のメンテナンス手順がない場合は、アプライアンスのカバーを再度取り付け、アプライアンスをラックに戻してケーブルを接続し、電源を投入します。


部品を交換した後、キットに同梱されているRMA手順書に記載されているとおりに、故障した部品をNetAppに返送してください。詳細については、 https://mysupport.netapp.com/site/info/rma["部品の返品と交換"^]ページを参照してください。

--
.NIC 3
--
.手順
. ESD リストバンドのストラップの端を手首に巻き付け、静電気の放電を防ぐためにクリップの端をメタルアースに固定します。
. 交換用NICをパッケージから取り出します。
. 交換用NICをライザーアセンブリに取り付けます。
+
.. 青色のラッチが開いた位置にあることを確認します。
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["ライザーアセンブリへのIOカードの取り付け"]

.. NICをライザーアセンブリ上のコネクタに位置合わせします。NICをコネクタに完全に差し込まれるまで慎重に押し込み、その後、青色のラッチを閉じます。


. ライザーアセンブリをシャーシに再取り付けします。
+
.. ライザーアセンブリをシャーシ内に配置する際は、ライザーアセンブリの端がシャーシの端と正しく位置合わせされていることを確認してください。
+
image:../media/drw_s2025_IO_3_replace_ieops-2686.svg["ライザーアセンブリ内のNIC 3を交換する"]

.. 青色のマークが付いた穴の横にある中心線に沿って、ライザーアセンブリを慎重に押し込み、完全に所定の位置に収まるまで押し込んでください。
.. ライザーにある青いロックを閉位置に回してください。


. ケーブルを再取り付けするNICポートから保護キャップを取り外します。
. アプライアンスで実行する他のメンテナンス手順がない場合は、アプライアンスのカバーを再度取り付け、アプライアンスをラックに戻してケーブルを接続し、電源を投入します。


部品を交換した後、キットに同梱されているRMA手順書に記載されているとおりに、故障した部品をNetAppに返送してください。詳細については、 https://mysupport.netapp.com/site/info/rma["部品の返品と交換"^]ページを参照してください。

--
====