---
permalink: installconfig/automating-configuration-of-storagegrid.html 
sidebar: sidebar 
keywords: automate, automating, automation, automatic, configuration, configure 
summary: グリッドノードのインストールと設定が完了したら、StorageGRID システムの設定を自動化できます。 
---
= StorageGRID の設定を自動化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードのインストールと設定が完了したら、StorageGRID システムの設定を自動化できます。

.作業を開始する前に
* インストールアーカイブにある次のファイルの場所を確認しておきます。
+
[cols="1a,1a"]
|===
| ファイル名 | 説明 


| configure-storagegrid.py  a| 
設定を自動化するための Python スクリプト



| storagegrid-sample.json を設定します  a| 
スクリプトで使用する構成ファイルの例



| storagegrid-bank.json を設定する  a| 
スクリプトで使用する空の構成ファイルです

|===
* を作成しておきます `configure-storagegrid.json` 構成ファイルこのファイルを作成するには、構成ファイルの例を変更します。 (`configure-storagegrid.sample.json`)または空の構成ファイル (`configure-storagegrid.blank.json`）。



CAUTION: 変更したファイルのパスワードセクションから管理パスワードとプロビジョニングパスフレーズを保存します。 `configure-storagegrid.json`構成ファイルを安全な場所に保管します。これらのパスワードは、インストール、拡張、およびメンテナンスの手順に必要です。変更したファイルもバックアップする必要があります `configure-storagegrid.json`構成ファイルを作成して安全な場所に保存します。

.このタスクについて
を使用できます `configure-storagegrid.py` Pythonスクリプトおよび `configure-storagegrid.json` StorageGRID システムの設定を自動化するための構成ファイル。


NOTE: またはを使用してシステムを設定することもできます https://docs.netapp.com/us-en/storagegrid/primer/exploring-grid-manager.html["Grid Manager の略"^]link:overview-of-installation-rest-apis.html["インストール API"]。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
たとえば、「+」と入力します
`cd StorageGRID-Webscale-_version/platform_`

+
ここで、 `_platform_` はです `debs`、 `rpms`または `vsphere`。

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.完了後
リカバリパッケージ `.zip` 設定プロセスでファイルが生成され、インストールと設定を実行するディレクトリにダウンロードされます。グリッドノードで障害が発生した場合に StorageGRID システムをリカバリできるようにするために、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


CAUTION: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムパスワードを生成するように指定した場合は、を展開する必要があります `Passwords.txt` ファイルを開き、StorageGRID システムへのアクセスに必要なパスワードを探します。

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----