---
permalink: installconfig/configuring-hardware.html 
sidebar: sidebar 
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: アプライアンスの電源を入れたら、StorageGRID で使用するネットワーク接続を設定します。  
---
= StorageGRID アプライアンスハードウェアをセットアップする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスの電源を入れたら、StorageGRID で使用するネットワーク接続を設定します。



== 必要なハードウェア構成



=== ネットワーク接続

すべてのアプライアンスについて、必要なネットワーク接続を設定し、確認する必要があります：

* link:../installconfig/accessing-storagegrid-appliance-installer.html["アプライアンスインストーラにアクセスします"]
* link:../installconfig/configuring-network-links.html["ネットワークリンクを設定する"]
* link:../installconfig/verifying-port-level-network-connections.html["ポートレベルのネットワーク接続を確認"]




=== BMCインターフェイス

次のいずれかのアプライアンスを設置する場合は、link:../installconfig/configuring-bmc-interface.html["ベースボード管理コントローラ（BMC）インターフェイスを設定します"]必要があります：

* SG100
* SG110
* SG120
* SG1000 からのアクセス
* SG1100
* SG1200
* SGF6024
* SGF6112を参照してください
* SGF6212
* SG6060 の設計
* SG6160
* SG6260


BMCインターフェイスを使用して、アプライアンスのSNMPやその他の低レベル設定を構成できます。また、ハードウェアのインストールに関するトラブルシューティング、アプライアンスの電源状態の判定、アプライアンスの識別用LEDの制御も可能です。

BMCで使用できる機能の詳細については、link:../commonhardware/use-bmc.html["BMCインターフェイスの使用"]を参照してください。



== オプションのハードウェア構成



=== SANtricity システムマネージャ

次のいずれかのアプライアンスをお持ちの場合、link:../installconfig/accessing-and-configuring-santricity-system-manager.html["SANtricity System Managerを設定する"]できます：

* SG5712
* SG5760
* SG5812
* SG5860
* SGF6024
* SG6060 の設計
* SG6160
* SG6260


SANtricity System Managerソフトウェアを使用すると、次のことが可能になります：

* アプライアンスのシステムパフォーマンスデータ、ハードウェアコンポーネントのステータス、およびサポート機能を監視
* ドライブのセキュリティキー、SNMP および syslog アラート、SANtricity System Manager にアクセスするための管理者パスワードを管理します
* EシリーズAutoSupportへのアクセスを設定




=== ノードまたはドライブの暗号化を有効にする

link:../installconfig/optional-enabling-node-encryption.html["ノードまたはドライブの暗号化を有効にする"]を使用して、アプライアンス内のドライブとディスクを保護できます。



=== RAIDモードを変更する

link:../installconfig/optional-changing-raid-mode.html["ストレージアプライアンスのRAIDモードを変更する"]ストレージとリカバリのニーズに対応できます。

以下のアプライアンスは RAID モードの変更に対応しています：

* SG5760
* SG5860
* SGF6024
* SG6060 の設計
* SG6160
* SG6260




=== ネットワークポートを再マッピングします

link:../installconfig/optional-remapping-network-ports-for-appliance.html["アプライアンスのネットワーク ポートを再マッピングする"]を使用してネットワーク接続を最適化できます。
