---
permalink: installconfig/deploying-appliance-storage-node.html 
sidebar: sidebar 
keywords: storage node, storage appliance, deploy node, deploying node, node, deploy, deploying 
summary: ストレージアプライアンスを設置して設定したら、 StorageGRID システムにストレージノードとして導入できます。アプライアンスをストレージノードとして導入する場合は、アプライアンスに搭載されている StorageGRID アプライアンスインストーラを使用します。 
---
= アプライアンスストレージノードを導入する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアプライアンスを設置して設定したら、 StorageGRID システムにストレージノードとして導入できます。アプライアンスをストレージノードとして導入する場合は、アプライアンスに搭載されている StorageGRID アプライアンスインストーラを使用します。

.作業を開始する前に
* アプライアンスノードをクローニングする場合は、の手順に進みます link:../commonhardware/appliance-node-cloning-procedure.html["アプライアンスノードのクローニング"] プロセス：
* アプライアンスをラックまたはキャビネットに設置し、ネットワークに接続し、電源を投入しておきます。
* StorageGRID アプライアンスインストーラを使用して、アプライアンスのネットワークリンク、 IP アドレス、ポートの再マッピング（必要な場合）を設定しておきます。
+

NOTE: ポート再マッピングのサポートは非推奨であり、将来のリリースでは削除される予定です。再マップされたポートを削除するには、 https://docs.netapp.com/us-en/storagegrid/maintain/removing-port-remaps.html["StorageGRIDアプライアンスのポート再マップを削除します"^] 。

* アプライアンスのコンピューティングコントローラに割り当てられている IP アドレスのいずれかを確認しておきます。接続されているどの StorageGRID ネットワークの IP アドレスでも使用できます。
* StorageGRID システムのプライマリ管理ノードを導入しておきます。
* StorageGRID アプライアンスインストーラの IP 設定ページに表示されるすべてのグリッドネットワークサブネットが、プライマリ管理ノードのグリッドネットワークサブネットリストで定義されている。
* サポートされている Web ブラウザがインストールされたサービスラップトップを用意しておきます。


.このタスクについて
各ストレージアプライアンスは単一のストレージノードとして機能します。すべてのアプライアンスは、グリッドネットワーク、管理ネットワーク、およびクライアントネットワークに接続できます

StorageGRID システムにアプライアンスストレージノードを導入するには、 StorageGRID アプライアンスインストーラにアクセスして次の手順を実行します。

* プライマリ管理ノードの IP アドレスおよびストレージノードの名前を指定または確認します。
* 導入を開始し、ボリュームの設定とソフトウェアのインストールが完了するまで待機します。
* アプライアンスインストールタスクの途中でインストールが一時停止した場合は、 Grid Manager にサインインしてすべてのグリッドノードを承認し、 StorageGRID のインストールプロセスと導入プロセスを完了すると、インストールを再開できます。



NOTE: 一度に複数のアプライアンスノードを導入する必要がある場合は、リンクを使用してインストールプロセスを自動化できます。../installconfig/automating-appliance-installation-and-configuration.html#automate-with-configure-sga-py-script[`configure-sga.py` アプライアンスインストールスクリプト]をクリックします。

* 拡張またはリカバリ処理を実行する場合は、該当する手順に従います。
+
** 既存のStorageGRIDシステムにアプライアンスストレージノードを追加するには、の手順を参照してください https://docs.netapp.com/us-en/storagegrid/expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html["グリッドノードを追加しています"^]。
** リカバリ処理の一環としてアプライアンスストレージノードを導入する場合は、手順を参照してください https://docs.netapp.com/us-en/storagegrid/maintain/recovering-storagegrid-appliance-storage-node.html["アプライアンスストレージノードのリカバリ"^]。




.手順
. ブラウザを開き、アプライアンスのコンピューティングコントローラの IP アドレスのいずれかを入力します。[+]
`*https://_Controller_IP_:8443*`
+
StorageGRID アプライアンスインストーラのホームページが表示されます。

. [ノードタイプ]*を選択します。詳細については、を参照してください https://docs.netapp.com/us-en/storagegrid/primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"]。
+

NOTE: Metadata-onlyは、アプライアンスの導入時にのみ選択できます。ストレージノードタイプとして[Metadata-Only]が選択されている場合、アプライアンスの導入後に変更することはできません。

. [ノード名]フィールドに、このアプライアンスノードに使用するシステム名を入力し、*[保存]*をクリックします。
+
ここで表示される名前は、アプライアンス ノードのシステム名になります。システム名は内部StorageGRID操作に必要であり、変更できません。アプライアンスノードの表示名を変更するには、 https://docs.netapp.com/us-en/storagegrid/maintain/rename-grid-site-node.html#how-to-rename-grid-sites-or-nodes["グリッド、サイト、ノードの名前を変更する方法"^] 。

. 「 * プライマリ管理ノード接続 * 」セクションで、プライマリ管理ノードの IP アドレスを指定する必要があるかどうかを判断します。
+
このデータセンターに他のノードがすでにインストールされている場合は、プライマリ管理ノードまたは ADMIN_IP が設定された少なくとも 1 つのグリッドノードが同じサブネットにあるという想定で、 StorageGRID アプライアンスインストーラがこの IP アドレスを自動的に検出します。

. この IP アドレスが表示されない場合や変更する必要がある場合は、アドレスを指定します。
+
[cols="1a,2a"]
|===
| オプション | 説明 


 a| 
IP を手動で入力します
 a| 
.. [管理ノードの検出を有効にする]*チェックボックスをオフにします。
.. IP アドレスを手動で入力します。
.. [ 保存（ Save ） ] をクリックします。
.. 新しい IP アドレスの接続状態が READY になるまで待ちます。




 a| 
接続されたすべてのプライマリ管理ノードの自動検出
 a| 
.. [管理ノードの検出を有効にする]*チェックボックスを選択します。
.. 検出された IP アドレスのリストが表示されるまで待ちます。
.. このアプライアンスストレージノードを導入するグリッドのプライマリ管理ノードを選択します。
.. [ 保存（ Save ） ] をクリックします。
.. 新しい IP アドレスの接続状態が READY になるまで待ちます。


|===
. [*インストール*]セクションで、現在の状態が「のインストール開始準備完了」であることを確認します `_node name_` をプライマリ管理ノードでグリッドに追加します `_admin_ip_` "*インストールの開始*ボタンが有効になっていることを確認します。
+
[Start Installation* （インストールの開始） ] ボタンが有効になっていない場合は、ネットワーク設定またはポート設定の変更が必要になることがあります。手順については、アプライアンスのメンテナンス手順を参照してください。

+

NOTE: ストレージノードアプライアンスをノードクローニングのターゲットとして導入する場合は、ここで導入プロセスを停止して、に進みます
link:../commonhardware/appliance-node-cloning-procedure.html["ノードクローニングの手順"]。

. StorageGRID アプライアンスインストーラのホームページで、 * インストールの開始 * をクリックします。
+
現在の状態が「Installation is in progress」に変わり、 link:../installconfig/monitoring-appliance-installation.html["[Monitor Installation]ページ"] が表示されます

+

NOTE: モニタのインストールページに手動でアクセスする必要がある場合は、 * モニタのインストール * をクリックします。

. グリッドに複数のアプライアンスストレージノードがある場合は、アプライアンスごとに上記の手順を繰り返します。
+

NOTE: 一度に複数のアプライアンスストレージノードを導入する必要がある場合は、リンク：../installconfig/automating-appliance-installation-and-configuration.html#automate-with-configure-sga-py-scriptを使用してインストールプロセスを自動化できます。[`configure-sga.py` アプライアンスインストールスクリプト]をクリックします。


