---
permalink: installconfig/monitoring-appliance-installation.html 
sidebar: sidebar 
keywords: appliance, installation, install, progress, monitor, status 
summary: StorageGRID アプライアンスインストーラでは、インストールが完了するまでステータスが提供されます。ソフトウェアのインストールが完了すると、アプライアンスがリブートされます。 
---
= アプライアンスの設置を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アプライアンスインストーラでは、インストールが完了するまでステータスが提供されます。ソフトウェアのインストールが完了すると、アプライアンスがリブートされます。

.手順
[role="tabbed-block"]
====
.ストレージアプライアンス
--
. インストールの進行状況を監視するには、 * インストールの監視 * をクリックします。
+
Monitor Installation ページにインストールの進行状況が表示されます。

+
青色のステータスバーは、現在進行中のタスクを示します。緑のステータスバーは、正常に完了したタスクを示します。

+

NOTE: インストーラは、以前のインストールで完了したタスクが再実行されないようにします。インストールを再実行している場合、再実行する必要のないタスクは緑色のステータスバーと「スキップ済み」のステータスで表示されます。

. インストールの最初の 2 つのステージの進行状況を確認します。
+
* 1 。ストレージの構成 *

+
インストーラがストレージコントローラに接続し、既存の設定をクリアし、設定されたRAIDモードに従ってRAIDを作成し、StorageGRID ソフトウェアとオブジェクトデータストレージにボリュームを割り当て、ホストを設定します。

+
※ 2OS * をインストールします

+
インストーラが StorageGRID のベースとなるオペレーティングシステムイメージをアプライアンスにコピーします。

. * StorageGRID のインストール * ステージが一時停止し、グリッド マネージャを使用して管理ノードでこのノードを承認するように求めるメッセージが埋め込みコンソールに表示されるまで、インストールの進行状況の監視を続行します。その後、次の手順に進みます。
. https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Grid Managerに移動"^]プライマリ管理ノードの、保留中のストレージノードを承認し、 StorageGRID のインストール プロセスを完了します。
+
Grid Manager から * Install * をクリックすると、ステージ 3 が完了し、ステージ 4 * Finalize Installation * が開始されます。ステージ 4 が完了すると、コントローラがリブートされます。



すべてのインストール段階が完了したら、ウィンドウを閉じます。

--
.サービスアプライアンス
--
. インストールの進行状況を監視するには、 * インストールの監視 * をクリックします。
+
Monitor Installation ページにインストールの進行状況が表示されます。

+
青色のステータスバーは、現在進行中のタスクを示します。緑のステータスバーは、正常に完了したタスクを示します。

+

NOTE: インストーラは、以前のインストールで完了したタスクが再実行されないようにします。インストールを再実行している場合、再実行する必要のないタスクは緑色のステータスバーと「スキップ済み」のステータスで表示されます。

. インストールの最初の 2 つのステージの進行状況を確認します。
+
* 1 。ストレージの構成 *

+
インストーラがアプライアンスのドライブから既存の設定を消去し、ホストを設定します。

+
※ 2OS * をインストールします

+
インストーラが StorageGRID のベースとなるオペレーティングシステムイメージをアプライアンスにコピーします。

. 次のいずれかのプロセスが実行されるまで、インストールの進行状況を監視します。
+
** プライマリ管理ノードを除くすべてのアプライアンスノードでは、 StorageGRIDのインストールステージが一時停止し、組み込みコンソールにメッセージが表示されます。このノードを管理者ノードで承認するように求められます。 https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Grid Manager の略"^] ;その後、次のステップに進みます。
** アプライアンスプライマリ管理ノードをインストールする場合は、ノードを承認する必要はありません。アプライアンスがリブートされます。次の手順は省略できます。
+

NOTE: アプライアンスプライマリ管理ノードのインストール中に、StorageGRIDインストーラをロードするための第5フェーズが表示されます（このスクリーンショットは最初の4つのフェーズのみを示しています）。StorageGRIDインストーラのロード（第5フェーズ）が10分以上進行中の場合は、Webページを手動で更新します。



. https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Grid Managerに移動"^]プライマリ管理ノードで、保留中のグリッドノードを承認し、StorageGRIDのインストールプロセスを完了します。
+
Grid Manager から * Install * をクリックすると、ステージ 3 が完了し、ステージ 4 * Finalize Installation * が開始されます。ステージ 4 が完了すると、アプライアンスがリブートされます。



すべてのインストール段階が完了したら、ウィンドウを閉じます。

--
====