---
permalink: installconfig/optional-changing-raid-mode.html 
sidebar: sidebar 
keywords: storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, RAID 6 
summary: 一部のアプライアンスモデルでは、ストレージとリカバリの要件に合わせてアプライアンス上で別のRAIDモードに変更できます。モードを変更できるのは、アプライアンスストレージノードを導入する前だけです。 
---
= オプション：RAIDモードを変更（SG5760およびSG6000）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一部のアプライアンスモデルでは、ストレージとリカバリの要件に合わせてアプライアンス上で別のRAIDモードに変更できます。モードを変更できるのは、アプライアンスストレージノードを導入する前だけです。

ConfigBuilderを使用してJSONファイルを生成する場合は、RAIDモードを自動的に変更できます。を参照してください link:automating-appliance-installation-and-configuration.html["アプライアンスのインストールと設定を自動化"]。

.このタスクについて
アプライアンスでサポートされている場合は、次のいずれかのボリューム構成オプションを選択できます。

* * Dynamic Disk Pools（DDP）*：データドライブ8本につきパリティドライブを2本使用します。すべてのアプライアンスに推奨されるデフォルトのモードです。DDPはRAID 6よりもシステムパフォーマンスに優れ、ドライブ障害が発生したあとのリビルド時間が短く、管理も容易です。DDPは、SG5760アプライアンスにドロワー損失からの保護も提供します。
+

NOTE: SG6060アプライアンスではSSDが2本あるため、DDPはドロワー損失からの保護を提供しません。ドロワー損失の保護は、SG6060に追加するすべての拡張シェルフで有効です。

* * DDP16 * ：このモードはデータドライブ 16 本につきパリティドライブを 2 本使用するため、 DDP よりもストレージ効率が高くなります。RAID 6と比較すると、システムパフォーマンスが向上し、ドライブ障害が発生したあとのリビルド時間が短縮され、管理が容易になり、ストレージ効率も同等に向上します。DDP16 モードを使用するには、構成にドライブが 20 本以上含まれている必要があります。ドロワー損失からの保護は提供しません。
* *RAID6 *: このモードは 16 台以上のデータドライブごとに 2 本のパリティドライブを使用します。これは、各ディスクでパリティストライプを使用するハードウェア保護方式であり、データが失われる前にRAIDセット内の2つのディスク障害を許容します。RAID 6 モードを使用するには、構成にドライブが 20 本以上含まれている必要があります。RAID 6はDDPよりもアプライアンスのストレージ効率を高めることができますが、ほとんどのStorageGRID 環境では推奨されません。



CAUTION: ボリュームがすでに構成されている場合や StorageGRID が事前にインストールされている場合に RAID モードを変更すると、ボリュームが削除されて置き換えられます。対象となったボリュームのデータはすべて失われます。

[role="tabbed-block"]
====
.SG5760
--
.作業を開始する前に
* 60本のドライブを搭載したSG5760があります。SG5712を使用している場合は、デフォルトのDDPモードを使用する必要があります。
* StorageGRID に接続できるクライアントを使用している必要があります。
* クライアントにはがあります https://docs.netapp.com/us-en/storagegrid-118/admin/web-browser-requirements.html["サポートされている Web ブラウザ"^]。


.手順
. サービスラップトップでWebブラウザを開き、StorageGRID アプライアンスインストーラの+にアクセスします
`*https://_E5700SG_Controller_IP_:8443*`
+
ここで `_E5700SG_Controller_IP_` E5700SGコントローラのいずれかのIPアドレスです。

. 「 * アドバンスト * 」 > 「 * RAID モード * 」の順に選択します。
. [Configure RAID Mode*] ページで、 [Mode] ドロップダウンリストから目的の RAID モードを選択します。
. [ 保存（ Save ） ] をクリックします。


--
.SG6000を使用します
--
.作業を開始する前に
* StorageGRID に接続できるクライアントを使用している必要があります。
* クライアントにはがあります  https://docs.netapp.com/us-en/storagegrid-118/admin/web-browser-requirements.html["サポートされている Web ブラウザ"^]。


.手順
. ブラウザを開き、アプライアンスのコンピューティングコントローラの IP アドレスのいずれかを入力します。
+
`*https://_Controller_IP_:8443*`

+
`_Controller_IP_` は、3つのStorageGRID ネットワークのいずれかでのコンピューティングコントローラ（ストレージコントローラではない）のIPアドレスです。

+
StorageGRID アプライアンスインストーラのホームページが表示されます。

. 「 * アドバンスト * 」 > 「 * RAID モード * 」の順に選択します。
. [Configure RAID Mode*] ページで、 [Mode] ドロップダウンリストから目的の RAID モードを選択します。
. [ 保存（ Save ） ] をクリックします。


--
====