= ステップ1：NICを取り外す
:allow-uri-read: 




== ステップ1：NICを取り外す

[role="tabbed-block"]
====
.NIC 1/NIC 2
--
.手順
. ESD リストバンドのストラップの端を手首に巻き付け、静電気の放電を防ぐためにクリップの端をメタルアースに固定します。
. アプライアンスの背面にあるNICを含むライザーアセンブリの場所を確認します。
. 故障したNICが搭載されたライザーの青色のロックラッチを上に回転させて開きます。
+
image:../media/drw_s2025_io_1_2_replace_ieops-2555.svg["ライザーアセンブリからNIC 1またはNIC 2を取り外す"]

. 青色のマークが付いた穴を使って、故障したNICが取り付けられたライザーアセンブリを慎重に上方に持ち上げてください。ライザーアセンブリを持ち上げるときは、シャーシの前方に向かって移動させてください。そうすることで、取り付けられているNICの外部コネクタがシャーシをクリアできるようになります。
. NIC にアクセスするには、ライザーを平らな帯電防止面の上に、金属フレーム側を下にして置いてください。
. 故障したNICの青いラッチを開け、ライザーアセンブリから慎重に取り外してください。NICをコネクタから取り外す際は、NICを少し揺らしてください。過度の力を加えないでください。
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["ライザーアセンブリからIOカードを取り外す"]

. ライザーとNICを平らな帯電防止面に置いてください。


--
.NIC 3
--
.手順
. ESD リストバンドのストラップの端を手首に巻き付け、静電気の放電を防ぐためにクリップの端をメタルアースに固定します。
. 故障したNICが付いているライザーの青いロックを回転させて、開位置にします。
+
image:../media/drw_s2025_io_3_replace_ieops-2556.svg["ライザーアセンブリからNIC 3を取り外す"]

. 青色のマークが付いた穴とライザーの端を使って、ライザーアセンブリを慎重に持ち上げてください。ライザーアセンブリを持ち上げるときは、シャーシの前方に向かって移動させてください。そうすることで、取り付けられているNICの外部コネクタがシャーシをクリアできるようになります。
. NIC にアクセスするには、ライザーを平らな帯電防止面の上に、金属フレーム側を下にして置いてください。
. 故障したNICの青いラッチを開け、ライザーアセンブリから慎重に取り外してください。NICをコネクタから取り外す際は、NICを少し揺らしてください。過度の力を加えないでください。
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["ライザーアセンブリからIOカードを取り外す"]

. ライザーとNICを平らな帯電防止面に置いてください。


--
====


== ステップ2：内蔵NICを再インストールする

取り外したNICと同じ場所に交換用NICを取り付けます。

[role="tabbed-block"]
====
.NIC 1/NIC 2
--
.手順
. ESD リストバンドのストラップの端を手首に巻き付け、静電気の放電を防ぐためにクリップの端をメタルアースに固定します。
. 交換用NICをパッケージから取り出します。
. 交換用NICをライザーアセンブリに取り付けます。
+
.. 青色のラッチが開いた位置にあることを確認します。
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["ライザーアセンブリへのIOカードの取り付け"]

.. NICをライザーアセンブリ上のコネクタに位置合わせします。NICをコネクタに完全に差し込まれるまで慎重に押し込み、その後、青色のラッチを閉じます。


. ライザーアセンブリをシャーシに再取り付けします。
+
.. ライザーアセンブリの位置合わせ穴の位置を確認し、システムボード上のガイドピンと一致させて、ライザーアセンブリが正しく配置されるようにします。
+
image:../media/drw_s2025_io_1_2_reinstall_ieops-2685.svg["ライザーアセンブリ内のNIC 1またはNIC 2の交換"]

.. ライザーアセンブリがシステム基板のコネクタおよびガイドピンに揃うように、ライザーアセンブリをシャーシに配置します。
.. ライザーアセンブリが完全に装着されるまで、青いマークの付いた穴の横にある中心線に沿って慎重に押し込みます。


. アプライアンスで実行する他のメンテナンス手順がない場合は、アプライアンスのカバーを再度取り付け、アプライアンスをラックに戻してケーブルを接続し、電源を投入します。


部品を交換した後、キットに同梱されているRMA手順書に記載されているとおりに、故障した部品をNetAppに返送してください。詳細については、 https://mysupport.netapp.com/site/info/rma["部品の返品と交換"^]ページを参照してください。

--
.NIC 3
--
.手順
. ESD リストバンドのストラップの端を手首に巻き付け、静電気の放電を防ぐためにクリップの端をメタルアースに固定します。
. 交換用NICをパッケージから取り出します。
. 交換用NICをライザーアセンブリに取り付けます。
+
.. 青色のラッチが開いた位置にあることを確認します。
+
image:../media/drw_s2025_IO_card_replace_ieops-2557.svg["ライザーアセンブリへのIOカードの取り付け"]

.. NICをライザーアセンブリ上のコネクタに位置合わせします。NICをコネクタに完全に差し込まれるまで慎重に押し込み、その後、青色のラッチを閉じます。


. ライザーアセンブリをシャーシに再取り付けします。
+
.. ライザーアセンブリをシャーシ内に配置する際は、ライザーアセンブリの端がシャーシの端と正しく位置合わせされていることを確認してください。
+
image:../media/drw_s2025_IO_3_replace_ieops-2686.svg["ライザーアセンブリ内のNIC 3を交換する"]

.. 青色のマークが付いた穴の横にある中心線に沿って、ライザーアセンブリを慎重に押し込み、完全に所定の位置に収まるまで押し込んでください。
.. ライザーにある青いロックを閉位置に回してください。


. ケーブルを再取り付けするNICポートから保護キャップを取り外します。
. アプライアンスで実行する他のメンテナンス手順がない場合は、アプライアンスのカバーを再度取り付け、アプライアンスをラックに戻してケーブルを接続し、電源を投入します。


部品を交換した後、キットに同梱されているRMA手順書に記載されているとおりに、故障した部品をNetAppに返送してください。詳細については、 https://mysupport.netapp.com/site/info/rma["部品の返品と交換"^]ページを参照してください。

--
====