---
permalink: sg6100/replace-6160-drives-60.html 
sidebar: sidebar 
keywords: E4000 replace drive, replacing E4000 drive, E4000 replace drive, replacing E4000 drive, E4000, sg6160, sg6100cn 
summary: E4000内のドライブを60ドライブシェルフと交換します。 
---
= ストレージコントローラシェルフまたは拡張シェルフのドライブの交換（SG6160）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG6160ストレージコントローラシェルフまたは拡張シェルフ（DE460C）内のドライブを交換することができます。

.このタスクについて
StorageGRID Grid Managerはストレージアレイのステータスを監視し、ドライブ障害が発生するとアラートを生成します。  Grid Managerがアラートを生成した場合、またはいつでも、SANtricity System ManagerのRecovery Guruを使用して、障害が発生した特定のドライブに関する詳細情報を確認できます。  ドライブで障害が発生すると黄色の警告 LED が点灯します。ストレージアレイで I/O を受信中に、障害が発生したドライブをホットスワップできます

.作業を開始する前に
* ドライブの取り扱い要件を確認します。
* 次のものがあることを確認します。
+
** ネットアップがコントローラシェルフまたはドライブシェルフにサポートする交換用ドライブ。
** ESD リストバンドを装着するか、静電気防止処置を施しておきます。
** SANtricityシステムマネージャへのアクセス：
+
*** Grid Managerで、* nodes *>*_appliance node_*>* SANtricity System Manager *を選択します。コントローラ情報は https://docs.netapp.com/us-en/storagegrid-118/monitor/viewing-santricity-system-manager-tab.html["SANtricityの[System Manager]タブ"]。
*** 管理ステーションのブラウザで、コントローラのドメイン名またはIPアドレスを指定します。








== 手順 1 ：ドライブを交換する準備をします

ドライブを交換する準備として、 SANtricity System Manager の Recovery Guru を確認し、前提となる手順を完了します。その後、障害が発生したコンポーネントを特定できます。

.手順
. SANtricity System Manager の Recovery Guru でドライブ障害の兆候が通知されましたが、ドライブがまだ使用停止になっていない場合は、 Recovery Guru の手順に従ってドライブを使用停止にします。
. 必要に応じて、 SANtricity System Manager を使用して、適切な交換用ドライブがあることを確認します。
+
.. 「 * ハードウェア * 」を選択します。
.. シェルフの図で障害が発生したドライブを選択します。
.. ドライブをクリックしてコンテキストメニューを表示し、 * 設定の表示 * を選択します。
.. 交換用ドライブの容量が交換するドライブと同じかそれよりも大きく、必要な機能を備えていることを確認します。


. 必要に応じて、 SANtricity System Manager を使用して、ストレージアレイ内のドライブの場所を特定します。
+
.. シェルフにベゼルがある場合は、ベゼルを取り外さないと LED は見えません。
.. ドライブのコンテキストメニューから、 * ロケーターライトを点灯 * を選択します。
+
ドライブドロワーの警告 LED （黄色）が点滅し、正しいドライブドロワーを開いて交換が必要なドライブを特定できます。



. 両方のレバーを引いてドライブドロワーを外します。
+
.. 伸ばしたレバーを使用して、ドライブドロワーを停止するところまで慎重に引き出します。
.. ドライブドロワーで各ドライブの前面の警告 LED を確認します。
+
各ドライブの前面の左側にあるドライブドロワーの警告 LED が点灯し、 LED のすぐ後ろのドライブハンドルに警告アイコンが表示されます。







== 手順 2 ：障害が発生したドライブを取り外す

新しいドライブに交換するために、障害が発生したドライブを取り外します。

.手順
. 交換用ドライブを開封し、静電気防止処置を施した平らな場所に置きます。
+
梱包材は、ドライブの返送が必要になったときのためにすべて保管しておいてください。

. 該当するドライブドロワーの両方のレバーをドロワーの外側に開きます。
. ドライブドロワーのレバーを慎重に引いて、ドライブドロワーをエンクロージャからは取り外さずに限界まで引き出します。
. 取り外すドライブの前面にあるオレンジのリリースラッチをそっと引いて戻します。
+
ドライブのカムハンドルが途中まで開き、ドライブがドロワーから外れます。

. カムハンドルを開き、ドライブを少し持ち上げます。
. 30 秒待ちます。
. カムハンドルをつかんでシェルフからドライブを持ち上げます。
. 近くに磁場がない、静電気防止処置を施したやわらかい場所にドライブを置きます。
. ドライブが取り外されたことがソフトウェアで認識されるまで 30 秒待ちます。
+

NOTE: アクティブなドライブを誤って取り外した場合は、少なくとも 30 秒待ってから再度取り付けてください。リカバリ手順については、ストレージ管理ソフトウェアを参照してください。





== 手順 3 ：新しいドライブを取り付ける

障害が発生したドライブの代わりに、新しいドライブを取り付けます。


CAUTION: 障害が発生したドライブを取り外したあと、できるだけ早く交換用ドライブを取り付けてください。そうしないと、機器が過熱状態になるリスクがあります。


CAUTION: * データアクセスが失われる可能性 * - ドライブドロワーをエンクロージャに戻すときは、乱暴に扱わないように十分に注意してください。ドロワーに衝撃を与えたり、ストレージアレイにぶつけて破損したりしないように、ゆっくりと押し込んでください。

.手順
. 新しいドライブのカムハンドルを垂直な位置まで持ち上げます。
. ドライブキャリアの両側にある 2 つの突起ボタンをドライブドロワーのドライブチャネルにある対応するくぼみに合わせます。
. ドライブを真上から下ろし、ドライブがオレンジのリリースラッチの下に完全に固定されるまでカムハンドルを下に回転させます。
. ドライブドロワーをエンクロージャに慎重に戻します。ドロワーに衝撃を与えたり、ストレージアレイにぶつけて破損したりしないように、ゆっくりと押し込んでください。
. 両方のレバーを内側に押してドライブドロワーを閉じます。
+
交換したドライブが正しく挿入されていれば、ドライブドロワーの前面にある緑のアクティビティ LED が点灯します。

+
構成によっては、データが新しいドライブに自動的に再構築される場合があります。シェルフでホットスペアドライブを使用している場合は、交換したドライブにデータをコピーする前に、ホットスペアへの完全な再構築が必要になることがあります。この再構築プロセスにより、この手順を完了するまでの時間が長くなります。





== 手順 4 ：ドライブの交換後の処理

新しいドライブが正しく動作していることを確認します。

.手順
. 交換したドライブの電源 LED と警告 LED を確認します。（最初にドライブを挿入したときに警告 LED が点灯することがありますが、問題がなければ 1 分以内に消灯します）。
+
** 電源 LED が点灯または点滅し、警告 LED が消灯している：新しいドライブが正しく動作しています。
** 電源 LED が消灯している：ドライブが正しく取り付けられていない可能性があります。ドライブを取り外し、 30 秒待ってから再度取り付けてください。
** 警告 LED が点灯している：新しいドライブが故障している可能性があります。別の新しいドライブと交換してください。


. SANtricity システムマネージャの Recovery Guru にまだ問題が表示されている場合、「 * 再確認」を選択して問題が解決されたことを確認してください。
. Recovery Guru でドライブの再構築が自動的に開始されなかったことが通知された場合は、次の手順に従って再構築を手動で開始します。
+

NOTE: この処理は、テクニカルサポートまたは Recovery Guru から指示があった場合にのみ実行してください。

+
.. 「 * ハードウェア * 」を選択します。
.. 交換したドライブをクリックします。
.. ドライブのコンテキストメニューで、「 * Reconstruct * 」を選択します。
.. この処理を実行することを確定します。
+
ドライブの再構築が完了すると、ボリュームグループの状態が「最適」になります。



. 必要に応じて、ベゼルを再度取り付けます。
. 障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。


.次の手順
これでドライブの交換は完了です。通常の運用を再開することができます。
