---
permalink: sg5700/replacing-e5700sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, Replacing, replace, E5700sg, controller, remove, removing, removal, install, installing, installation 
summary: E5700SG コントローラが適切に機能しない場合や障害が発生した場合は、交換が必要となることがあります。 
---
= E5700SGコンピューティングコントローラの交換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E5700SG コントローラが適切に機能しない場合や障害が発生した場合は、交換が必要となることがあります。

.作業を開始する前に
* 交換するコントローラと同じパーツ番号の交換用コントローラを用意しておきます。
* 障害が発生した E5700 コントローラを交換するための E シリーズの手順書をダウンロードしておきます。
+

NOTE: E シリーズの手順書は、特定の手順の詳細を知る必要がある場合のみ参照してください。StorageGRID アプライアンスのコントローラを交換する際は、Eシリーズの手順書を参考にしないでください。手順が異なります。たとえば、 E5700 コントローラ向けの E シリーズの手順書では、障害が発生したコントローラからバッテリとホストインターフェイスカード（ HIC ）を取り外して交換用コントローラに取り付ける方法が説明されています。この手順はE5700SGコントローラには適用されません。

* コントローラに接続する各ケーブルを識別するためのラベルを用意しておきます。


.このタスクについて
コントローラを交換すると、アプライアンスストレージノードにアクセスできなくなります。E5700SG コントローラが動作している場合は、この手順 の起動時に通常の方法でシャットダウンを実行してください。


NOTE: StorageGRID ソフトウェアをインストールする前にコントローラを交換すると、この手順 の完了後すぐに StorageGRID アプライアンスインストーラにアクセスできない場合があります。StorageGRID アプライアンスインストーラには、アプライアンスと同じサブネット上の他のホストからはアクセスできますが、他のサブネット上のホストからはアクセスできません。この状態は 15 分以内に（元のコントローラのいずれかの ARP キャッシュエントリがタイムアウトした時点で）自動的に解消されます。あるいは、古い ARP キャッシュエントリをローカルルータまたはゲートウェイから手動でパージすれば、すぐにこの状態を解消できます。

.手順
. E5700SGコントローラをシャットダウンします。
+
.. グリッドノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



.. E5700SGコントローラのをシャットダウンしてください：+
`*shutdown -h now*`
.. キャッシュメモリ内のデータがドライブに書き込まれるまで待ちます。
+
キャッシュされたデータをドライブに書き込む必要がある場合は、 E2800 コントローラの背面にある緑のキャッシュアクティブ LED が点灯します。この LED が消灯するまで待つ必要があります。



. 電源をオフにします。
+
.. SANtricity システムマネージャのホームページで、「 * 進行中の処理を表示」を選択します。
.. すべての処理が完了したことを確認します。
.. アプライアンスの両方の電源スイッチをオフにします。
.. すべての LED が消灯するまで待ちます。


. コントローラに接続されている StorageGRID ネットワークが DHCP サーバを使用している場合は、次の作業を行い
+
.. 交換用コントローラのポートの MAC アドレス（コントローラのラベルに記載）を書き留めます。
.. ネットワーク管理者に元のコントローラの IP アドレス設定を更新するよう依頼して、交換用コントローラの MAC アドレスを反映させます。
+

CAUTION: 交換用コントローラに電源を投入する前に、元のコントローラの IP アドレスが更新されたことを確認する必要があります。そうしないと、コントローラのブート時に新しい DHCP IP アドレスが取得されて、 StorageGRID に再接続できなくなることがあります。この手順では、コントローラに接続されているすべての StorageGRID ネットワークを環境 接続します。



. コントローラをアプライアンスから取り外します。
+
.. ESD リストバンドを装着するか、静電気防止処置を施します。
.. ケーブルにラベルを付け、ケーブルと SFP を外します。
+

NOTE: パフォーマンスの低下を防ぐため、ケーブルをねじったり、折り曲げたり、挟んだり、踏んだりしないでください。

.. カムハンドルのラッチを押してコントローラをアプライアンスから外し、カムハンドルを右側に開きます。
.. 両手でカムハンドルをつかみ、コントローラをスライドしてアプライアンスから引き出します。
+

CAUTION: コントローラは重いので、必ず両手で支えながら作業してください。



. 交換用コントローラをアプライアンスに取り付けます。
+
.. 取り外し可能なカバーが下になるようにコントローラを裏返します。
.. カムハンドルを開いた状態でコントローラをスライドし、アプライアンスに最後まで挿入します。
.. カムハンドルを左側に動かして、コントローラを所定の位置にロックします。
.. ケーブルと SFP を交換します。


. アプライアンスの電源を入れ、コントローラの LED とデジタル表示ディスプレイを監視します。
+
コントローラが正常にブートされると、デジタル表示ディスプレイに次のコードが表示されます。

+
** E2800シリーズコントローラ：
+
最後の状態はです `99`。

** E5700SGコントローラ：
+
最後の状態はです `HA`。



. アプライアンスストレージノードが Grid Manager に表示され、アラームが表示されていないことを確認します。


部品の交換後、障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"^] 詳細については、を参照してください。

.関連情報
https://docs.netapp.com/us-en/e-series-family/index.html["NetApp Eシリーズのドキュメント"^]
