---
permalink: sg5700/troubleshoot-upgrading-drive-firmware-using-santricity-system-manager.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, troubleshoot, storage node, storage appliance, upgrade, upgrading, firmware, drive, disk, SANtricity System Manager, SANtricity 
summary: SANtricity System Managerを使用してアプライアンスのドライブのファームウェアをアップグレードするときに発生する可能性があるエラーのトラブルシューティングを行います。 
---
= ドライブファームウェアのアップグレードエラーのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Managerを使用してアプライアンスのドライブのファームウェアをアップグレードするときに発生する可能性があるエラーのトラブルシューティングを行います。

* * 割り当て済みドライブの障害 *
+
** エラーの理由の 1 つとして、ドライブに適切な署名がない可能性があります。該当するドライブが認定済みのドライブであることを確認します。詳細については、テクニカルサポートにお問い合わせください。
** ドライブを交換する場合は、交換用ドライブの容量が交換する障害ドライブと同じかそれよりも大きいことを確認してください。
** 障害が発生したドライブの交換は、ストレージアレイで I/O を受信中に実行できます


* * ストレージアレイを確認してください *
+
** 各コントローラに IP アドレスが割り当てられていることを確認します。
** コントローラに接続されているすべてのケーブルが破損していないことを確認します。
** すべてのケーブルがしっかりと接続されていることを確認します。


* * 内蔵ホットスペアドライブ *
+
ファームウェアをアップグレードする前に、このエラーを修正する必要があります。

* * 不完全なボリュームグループ *
+
1 つ以上のボリュームグループまたはディスクプールが不完全な場合は、ファームウェアをアップグレードする前に、このエラーを修正する必要があります。

* * すべてのボリュームグループで実行中の排他的な処理（バックグラウンドメディア / パリティスキャン以外） *
+
1 つ以上の排他的な処理を実行中の場合は、その処理を完了してからファームウェアをアップグレードする必要があります。System Manager で処理の進捗状況を監視します。

* * 見つからないボリューム *
+
ファームウェアをアップグレードする前に、ボリュームが見つからない状態を修正する必要があります。

* * いずれかのコントローラが最適以外の状態 *
+
いずれかのストレージアレイコントローラを確認する必要があります。ファームウェアをアップグレードする前に、この状態を修正する必要があります。

* * コントローラオブジェクトグラフ間でストレージパーティション情報が一致しません *
+
コントローラ上のデータの検証中にエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。

* * SPM によるデータベースコントローラの検証が失敗します *
+
コントローラでストレージパーティションマッピングデータベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。

* * 構成データベースの検証（ストレージアレイのコントローラのバージョンでサポートされている場合） *
+
コントローラで構成データベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。

* * MEL 関連のチェック *
+
この問題を解決するには、テクニカルサポートにお問い合わせください。

* * 過去 7 日間に 10 個を超える DDE 情報または重大 MEL イベントが報告されました *
+
この問題を解決するには、テクニカルサポートにお問い合わせください。

* * 過去 7 日間に 2 ページ 2C 重大 MEL イベントが報告されました *
+
この問題を解決するには、テクニカルサポートにお問い合わせください。

* * 過去 7 日間に 2 個以上の低下したドライブチャネル重大 MEL イベントが報告されました *
+
この問題を解決するには、テクニカルサポートにお問い合わせください。

* * 過去 7 日間に 4 個を超える重大 MEL エントリがあります *
+
この問題を解決するには、テクニカルサポートにお問い合わせください。


