---
permalink: sg5800/replace-cmos-battery-sg5800.html 
sidebar: sidebar 
keywords: cmos, battery, replace, sg5800, controller 
summary: システムのサービスとアプリケーションが正確な時間同期を保ち、正常に機能し続けるためには、SG5800 コントローラの CMOS バッテリを交換する必要がある場合があります。 
---
= SG5800コントローラのCMOSバッテリを交換する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムのサービスとアプリケーションが正確な時間同期を保ち、正常に機能し続けるためには、SG5800 コントローラの CMOS バッテリを交換する必要がある場合があります。

.このタスクについて
CMOS バッテリを交換すると、アプライアンスの Storage Node にアクセスできなくなります。サービスの中断を防ぐには、CMOS バッテリの交換を開始する前に、他のすべての Storage Node がグリッドに接続されていることを確認するか、サービスの中断期間が許容される、スケジュールされたメンテナンス ウィンドウ中にバッテリを交換します。



== ステップ1：SG5800コントローラをシャットダウンする

.手順
. グリッドノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@grid_node_IP`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. SG5800コントローラをシャットダウンします。
+
*`shutdown -h now`*





== ステップ2：アプライアンスからコントローラを取り外す

.手順
. ESD リストバンドを装着するか、静電気防止処置を施します。
. ケーブルにラベルを付け、ケーブルと SFP を外します。
+

NOTE: パフォーマンスの低下を防ぐため、ケーブルをねじったり、折り曲げたり、挟んだり、踏んだりしないでください。

. カムハンドルのラッチを押してコントローラをアプライアンスから外し、カムハンドルを右側に開きます。
. 両手でカムハンドルをつかみ、コントローラをスライドしてアプライアンスから引き出します。
+

NOTE: コントローラは重いので、必ず両手で支えながら作業してください。

. コントローラ モジュールを裏返し、平らで安定した場所に置きます。
. コントローラモジュールの側面にある青いボタンを押してカバーを開き、カバーを上に回転させてコントローラモジュールから取り外します。
+
image::../media/drw_sg5800_open_controller_module_cover_IEOPS-695.svg[SG5800コントローラーモジュールカバーを開く]





== ステップ3：CMOSバッテリーを交換する

.手順
. CMOSバッテリの場所を確認します。
+
image::../media/drw_sg5800_replace_rtc_battery_IEOPS-701.svg[SG5800コントローラのCMOSバッテリーの場所]

+

NOTE: コントローラーの外観は、図に示されているものと異なる場合があります。ただし、CMOS バッテリーの位置は同じです。

. バッテリーをホルダーからゆっくりと押して回転させ、機器から持ち上げて取り出します。
+

NOTE: ホルダーから取り外す際に、バッテリの極の向きを確認しておいてください。バッテリに記載されているプラス記号に従って、バッテリをホルダーに正しく配置する必要があります。正しいバッテリの向きを示すため、ホルダーの近くにプラス記号が表示されています。

. 交換用バッテリを静電気防止用の梱包バッグから取り出します。
. コントローラ モジュールで空のバッテリ ホルダーの場所を確認します。
. CMOSバッテリの極の向きを確認し、バッテリを斜めに傾けた状態で押し下げてホルダーに挿入します。
. バッテリがホルダーに完全に取り付けられ、かつ極の向きが正しいことを目で見て確認します。
. コントローラーカバーを再度取り付けます。




== ステップ4：コントローラをアプライアンスに再インストールする

.手順
. コントローラをアプライアンスにインストールします：
+
.. 取り外し可能なカバーが下を向くようにコントローラーを裏返します。
.. カムハンドルを開いた状態でコントローラをスライドし、アプライアンスに最後まで挿入します。
.. カムハンドルを左側に動かして、コントローラを所定の位置にロックします。
.. ケーブルを再接続します。


. コントローラが再起動し、アプライアンスがグリッドに再参加したら、アプライアンスのストレージ ノードがグリッド マネージャーに表示され、アラームが表示されないことを確認します。


部品の交換後、障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"] 詳細については、を参照してください。
