---
permalink: sg5800/replace-drives-12-24.html 
sidebar: sidebar 
keywords: E4000 replace drive, replacing E4000 drive, E4000 replace drive, replacing E4000 drive, E4000, E-Series, eseries. sg5812 
summary: SG5812のドライブを交換することができます。 
---
= SG5812のドライブの交換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG5812のドライブを交換することができます。

.このタスクについて
StorageGRID Grid Managerはアプライアンスのステータスを監視し、ドライブ障害が発生するとアラートを生成します。  Grid Managerがアラートを生成した場合、またはいつでも、SANtricity System ManagerのRecovery Guruを使用して、障害が発生した特定のドライブに関する詳細情報を確認できます。  ドライブで障害が発生すると黄色の警告 LED が点灯します。ストレージアレイで I/O を受信中に、障害が発生したドライブをホットスワップできます

.作業を開始する前に
* ドライブの取り扱い要件を確認
* 次のものがあることを確認します。
+
** ネットアップがコントローラシェルフまたはドライブシェルフにサポートする交換用ドライブ。
** ESD リストバンドを装着するか、静電気防止処置を施しておきます。
** コントローラの SANtricity System Manager にアクセスできるブラウザを備えた管理ステーション。（ System Manager インターフェイスを開くには、ブラウザでコントローラのドメイン名または IP アドレスを指定します）。






== 手順 1 ：ドライブを交換する準備をします

ドライブを交換する準備として、 SANtricity System Manager の Recovery Guru を確認し、前提となる手順を完了します。その後、障害が発生したコンポーネントを特定できます。

.手順
. SANtricity System Manager の Recovery Guru でドライブ障害の兆候が通知されましたが、ドライブがまだ使用停止になっていない場合は、 Recovery Guru の手順に従ってドライブを使用停止にします。
. 必要に応じて、 SANtricity System Manager を使用して、適切な交換用ドライブがあることを確認します。
+
.. 「 * ハードウェア * 」を選択します。
.. シェルフの図で障害が発生したドライブを選択します。
.. ドライブをクリックしてコンテキストメニューを表示し、 * 設定の表示 * を選択します。
.. 交換用ドライブの容量が交換するドライブと同じかそれよりも大きく、必要な機能を備えていることを確認します。
+
たとえば、ハードディスクドライブ（ HDD ）はソリッドステートディスク（ SSD ）とは交換しないでください。同様に、セキュリティ対応ドライブを交換する場合は、交換用ドライブもセキュリティ対応であることを確認してください。



. 必要に応じて、 SANtricity System Manager を使用して、ストレージアレイ内のドライブの場所を特定します。ハードウェアページのドライブのコンテキストメニューから、 * ロケーターライトを点灯 * を選択します。
+
ドライブの警告 LED （黄色）が点滅し、交換が必要なドライブを特定できます。

+

NOTE: ドライブを交換するシェルフにベゼルがある場合は、ベゼルを取り外さないとドライブ LED は見えません。





== 手順 2 ：障害が発生したドライブを取り外す

新しいドライブに交換するために、障害が発生したドライブを取り外します。

.手順
. 交換用ドライブを開封し、静電気防止処置を施した平らな場所に置きます。
+
梱包材はすべて保管しておいてください。

. 障害が発生したドライブのリリースボタンを押します。
. カムハンドルを開き、ドライブを少し引き出します。
. 30 秒待ちます。
. ドライブをシェルフから両手で取り外します。
. 近くに磁場がない、静電気防止処置を施したやわらかい場所にドライブを置きます。
. ドライブが取り外されたことがソフトウェアで認識されるまで 30 秒待ちます。
+

NOTE: アクティブなドライブを誤って取り外した場合は、少なくとも 30 秒待ってから再度取り付けてください。リカバリ手順については、ストレージ管理ソフトウェアを参照してください。





== 手順 3 ：新しいドライブを取り付ける

障害が発生したドライブの代わりに、新しいドライブを取り付けます。


CAUTION: 障害が発生したドライブを取り外したあと、できるだけ早く交換用ドライブを取り付けてください。そうしないと、機器が過熱状態になるリスクがあります。

.手順
. カムハンドルを開きます。
. 空いているベイに交換用ドライブを両手で挿入し、動かなくなるまでしっかりと押し込みます。
. ドライブがミッドプレーンに完全に収まり、カチッという音がして固定されるまで、カムハンドルをゆっくりと閉じます。
+
ドライブが正しく挿入されていれば、ドライブの緑の LED が点灯します。

+

NOTE: 構成によっては、データが新しいドライブに自動的に再構築される場合があります。シェルフでホットスペアドライブを使用している場合は、交換したドライブにデータをコピーする前に、ホットスペアへの完全な再構築が必要になることがあります。この再構築プロセスにより、この手順を完了するまでの時間が長くなります。





== 手順 4 ：ドライブの交換後の処理

ドライブの交換が完了したら、新しいドライブが正しく動作していることを確認します。

.手順
. 交換したドライブの電源 LED と警告 LED を確認します。（最初にドライブを挿入したときに警告 LED が点灯することがありますが、問題がなければ 1 分以内に消灯します）。
+
** 電源 LED が点灯または点滅し、警告 LED が消灯している：新しいドライブが正しく動作しています。
** 電源 LED が消灯している：ドライブが正しく取り付けられていない可能性があります。ドライブを取り外し、 30 秒待ってから再度取り付けてください。
** 警告 LED が点灯している：新しいドライブが故障している可能性があります。別の新しいドライブと交換してください。


. SANtricity システムマネージャの Recovery Guru にまだ問題が表示されている場合、「 * 再確認」を選択して問題が解決されたことを確認してください。
. Recovery Guru でドライブの再構築が自動的に開始されなかったことが通知された場合は、次の手順に従って再構築を手動で開始します。
+

NOTE: この処理は、テクニカルサポートまたは Recovery Guru から指示があった場合にのみ実行してください。

+
.. 「 * ハードウェア * 」を選択します。
.. 交換したドライブをクリックします。
.. ドライブのコンテキストメニューで、「 * Reconstruct * 」を選択します。
.. この処理を実行することを確定します。
+
ドライブの再構築が完了すると、ボリュームグループの状態が「最適」になります。



. 必要に応じて、ベゼルを再度取り付けます。
. 障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。


.次の手順
これでドライブの交換は完了です。通常の運用を再開することができます。
