---
permalink: commonhardware/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: アプライアンスノードをクローニングする前に、考慮事項と要件を理解しておく必要があります。 
---
= アプライアンスノードのクローニングに関する考慮事項と要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスノードをクローニングする前に、考慮事項と要件を理解しておく必要があります。



== 交換用アプライアンスのハードウェア要件

交換用アプライアンスが次の基準を満たしていることを確認します。

* ソースノード（交換するアプライアンス）とターゲット（新しい）アプライアンスは、同じタイプのアプライアンスである必要があります。
+
** クローニングできるのは、管理ノードアプライアンスまたはゲートウェイノードアプライアンスだけです。
** クローニングできるのは、新しいストレージアプライアンスに対してのみです。


* 管理ノードまたはゲートウェイノードのアプライアンスの場合、ソースノードのアプライアンスとターゲットのアプライアンスが同じタイプである必要はありませんが、アプライアンスのタイプを変更するには、ケーブルまたはSFPモジュールの交換が必要になることがあります。
+
たとえば、 SG1000 ノードアプライアンスを SG100 に交換したり、 SG100 アプライアンスを SG1000 アプライアンスに交換したりできます。

* ストレージノードアプライアンスの場合、ソースノードアプライアンスとターゲットアプライアンスが同じタイプのアプライアンスである必要はありませんが、ターゲットアプライアンスのストレージ容量はソースアプライアンスよりも大きくする必要があります。
+
たとえば、SG5700ノードアプライアンスをSG6000アプライアンスと交換できます。



StorageGRID 環境の特定のアプライアンスノードをクローニングする互換性のある交換用アプライアンスを選択する方法については、 StorageGRID の営業担当者にお問い合わせください。



== アプライアンスノードのクローンを作成する準備をします

アプライアンスノードをクローニングするには、次の情報が必要です。

* グリッドネットワークの一時的な IP アドレスをネットワーク管理者から取得し、最初のインストール時にターゲットアプライアンスで使用します。ソースノードが管理ネットワークまたはクライアントネットワークに属している場合は、それらのネットワークの一時的な IP アドレスを取得します。
+
一時的なIPアドレスは通常、クローニングするソースノードのアプライアンスと同じサブネット上にあり、クローニングの完了後は不要です。クローニング接続を確立するには、ソースアプライアンスとターゲットアプライアンスの両方が StorageGRID のプライマリ管理ノードに接続されている必要があります。

* データ転送トラフィックのクローニングに使用するネットワークを決定し、 StorageGRID ネットワークのパフォーマンスやデータの可用性を低下させることなく、最高のデータ転送パフォーマンスを実現します。
+

NOTE: 1GbE 管理ネットワークを使用したクローニングでデータ転送を行うと、クローニングに時間がかかります。

* ターゲットアプライアンスでキー管理サーバ（ KMS ）を使用したノード暗号化が使用されるかどうかを確認し、クローニングを実行する前に最初のターゲットアプライアンスインストール時にノードの暗号化を有効にできるようにします。ソースアプライアンスノードでノード暗号化が有効になっているかどうかを確認できます（を参照） link:../installconfig/optional-enabling-node-encryption.html["ノード暗号化を有効にします"]。
+
ソースノードとターゲットアプライアンスで、異なるノード暗号化設定を使用できます。データの復号化と暗号化は、データ転送中、およびターゲットノードが再起動してグリッドに参加したときに自動的に実行されます。

* ターゲット・アプライアンスの RAID モードをデフォルト設定から変更するかどうかを決定します。このため、この情報は、クローニングの前にターゲット・アプライアンスを最初にインストールするときに指定できます。ソースアプライアンスノードの現在の RAID モードに関する情報は、 Grid Manager の * nodes * ページで確認できます。アプライアンスの [*Storage*] タブを選択します。
+
ソースノードとターゲットアプライアンスでは、 RAID 設定が異なる場合があります。

* ノードのクローニングプロセスを完了するための十分な時間を計画します。稼働中のストレージノードからターゲットアプライアンスにデータを転送するために、数日かかる場合があります。クローニングのスケジュールを一度に設定して、ビジネスへの影響を最小限に抑えることができます。
* クローニングするアプライアンスノードは一度に 1 つだけにしてください。クローニングによって、 StorageGRID の他のメンテナンス機能を同時に実行することはできません。
* アプライアンスノードのクローンを作成したら、互換性のある別のノードアプライアンスのクローンを作成するために、インストール前の状態に戻ったソースアプライアンスをターゲットとして使用できます。

