---
permalink: commonhardware/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: アプライアンスノードをクローニングする前に、考慮事項と要件を理解しておく必要があります。 
---
= アプライアンスノードのクローニングに関する考慮事項と要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスノードをクローニングする前に、考慮事項と要件を理解しておく必要があります。


TIP: ゲートウェイ ノードではノード クローンが無効になっています。ゲートウェイ ノードを交換するには、ゲートウェイ ノードを廃止してから、拡張を実行して新しいアプライアンス ゲートウェイ ノードを追加します。ゲートウェイ ノードの廃止および拡張手順は、ストレージ ノードの場合よりもはるかに高速です。



== 交換用アプライアンスのハードウェア要件

交換用アプライアンスが次の基準を満たしていることを確認します。

* ソースノード（交換するアプライアンス）とターゲット（新しい）アプライアンスは、同じタイプのアプライアンスである必要があります。
+
** 管理ノード アプライアンスのクローンを新しいサービス アプライアンスに作成することのみが可能です。
** クローニングできるのは、新しいストレージアプライアンスに対してのみです。


* 管理ノード アプライアンスの場合、ソース ノード アプライアンスとターゲット アプライアンスは同じアプライアンス モデルである必要はありません。ただし、アプライアンス モデルを変更すると、ケーブルまたは SFP モジュールの交換が必要になる場合があります。
+
たとえば、 SG1000 ノードアプライアンスを SG100 に交換したり、 SG100 アプライアンスを SG1000 アプライアンスに交換したりできます。

* ストレージノードアプライアンスの場合、ソースノードアプライアンスとターゲットアプライアンスが同じタイプのアプライアンスである必要はありませんが、次の点に注意してください。
+
** ターゲットアプライアンスには、ソースアプライアンスよりも大きなストレージ容量が必要です。
+
たとえば、SG5700ノードアプライアンスをSG6000アプライアンスと交換できます。

** ターゲットアプライアンスには、ソースアプライアンスと同数以上のオブジェクトストレージボリュームが必要です。
+
たとえば、SG6000 ノード アプライアンス (16 個のオブジェクト ストア ボリューム) を SGF6112 アプライアンス (12 個のオブジェクト ストア ボリューム) に置き換えることはできません。





StorageGRID 環境の特定のアプライアンスノードをクローニングする互換性のある交換用アプライアンスを選択する方法については、 StorageGRID の営業担当者にお問い合わせください。



== アプライアンスノードのクローンを作成する準備をします

アプライアンスノードをクローニングするには、次の情報が必要です。

* グリッドネットワークの一時的な IP アドレスをネットワーク管理者から取得し、最初のインストール時にターゲットアプライアンスで使用します。ソースノードが管理ネットワークまたはクライアントネットワークに属している場合は、それらのネットワークの一時的な IP アドレスを取得します。
+
一時的なIPアドレスは通常、クローニングするソースノードのアプライアンスと同じサブネット上にあり、クローニングの完了後は不要です。クローニング接続を確立するには、ソースアプライアンスとターゲットアプライアンスの両方が StorageGRID のプライマリ管理ノードに接続されている必要があります。

* データ転送トラフィックのクローニングに使用するネットワークを決定し、 StorageGRID ネットワークのパフォーマンスやデータの可用性を低下させることなく、最高のデータ転送パフォーマンスを実現します。
+

NOTE: 1GbE 管理ネットワークを使用したクローニングでデータ転送を行うと、クローニングに時間がかかります。

* クローン作成前の最初のターゲット アプライアンスのインストール中にノード暗号化を有効にできるように、ターゲット アプライアンスでキー管理サーバー (KMS) を使用してノード暗号化を使用するかどうかを決定してください。ソースアプライアンスノードでノード暗号化が有効になっているかどうかは、link:../installconfig/optional-enabling-node-encryption.html["ノード暗号化を有効にします"] 。
+
ソース ノードとターゲット アプライアンスでは、次の例外を除いて、異なるノード暗号化設定を持つことができます。次のアプライアンスでは、暗号化されていないノード ソースからノード暗号化されたターゲットへのノードのクローン作成はサポートされていません。

+
** ノード暗号化なしの SGF6112 ノードアプライアンスからノード暗号化ありの SGF6112 ノードアプライアンスへ
** ノード暗号化なしの SG1100 ノードアプライアンスからノード暗号化ありの SG1100 ノードアプライアンスへ
** ノード暗号化なしの SG110 ノードアプライアンスからノード暗号化ありの SG110 ノードアプライアンスへ


+
データの復号化と暗号化は、データ転送中、およびターゲット ノードが再起動してグリッドに参加するときに自動的に実行されます。

* ターゲット・アプライアンスの RAID モードをデフォルト設定から変更するかどうかを決定します。このため、この情報は、クローニングの前にターゲット・アプライアンスを最初にインストールするときに指定できます。ソースアプライアンスノードの現在の RAID モードに関する情報は、 Grid Manager の * nodes * ページで確認できます。アプライアンスの*[ハードウェア]*タブを選択します。
+
ソースノードとターゲットアプライアンスでは、 RAID 設定が異なる場合があります。

* ノードのクローニングプロセスを完了するための十分な時間を計画します。稼働中のストレージノードからターゲットアプライアンスにデータを転送するために、数日かかる場合があります。クローニングのスケジュールを一度に設定して、ビジネスへの影響を最小限に抑えることができます。
* クローニングするアプライアンスノードは一度に 1 つだけにしてください。クローニングによって、 StorageGRID の他のメンテナンス機能を同時に実行することはできません。
* アプライアンスノードのクローンを作成したら、互換性のある別のノードアプライアンスのクローンを作成するために、インストール前の状態に戻ったソースアプライアンスをターゲットとして使用できます。

