---
permalink: commonhardware/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: StorageGRID でアプライアンスノードをクローニングして、アプライアンスの設計や機能を強化することができます。クローニングを実行すると、既存のノードに関するすべての情報が新しいアプライアンスに転送され、ハードウェアのアップグレードプロセスを簡単に実行できます。また、アプライアンスの運用停止や拡張を行う代わりに、アプライアンスを交換することもできます。 
---
= アプライアンスノードのクローニング：概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID でアプライアンスノードをクローニングして、アプライアンスの設計や機能を強化することができます。クローニングを実行すると、既存のノードに関するすべての情報が新しいアプライアンスに転送され、ハードウェアのアップグレードプロセスを簡単に実行できます。また、アプライアンスの運用停止や拡張を行う代わりに、アプライアンスを交換することもできます。

アプライアンスノードのクローニングを使用すると、グリッド内の既存のアプライアンスノード（ソース）を、同じ論理 StorageGRID サイトに含まれる互換性のあるアプライアンス（ターゲット）に簡単に置き換えることができます。このプロセスでは、すべてのデータが新しいアプライアンスに転送され、古いアプライアンスノードを交換するためにアプライアンスが稼働中になり、古いアプライアンスは設置前の状態になります。



== アプライアンスノードをクローニングする理由

アプライアンスノードは、次の処理が必要な場合にクローニングできます。

* 寿命が近づいているアプライアンスの交換
* 改善されたアプライアンステクノロジを活用するには、既存のノードをアップグレードしてください。
* StorageGRID システム内のストレージノードの数を変更することなく、グリッドのストレージ容量を拡張できます。
* RAID モードを DDP 8 から DDP 16 に変更する、 RAID 6 に変更するなどして、ストレージ効率を向上
* ノード暗号化を効率的に実装して、外部キー管理サーバ（ KMS ）を使用できるようにします。




== どの StorageGRID ネットワークが使用されていますか？

クローニングでは、 3 つの StorageGRID ネットワークのいずれかで、ソースノードからターゲットアプライアンスにデータが直接転送されます。グリッドネットワークは通常は使用されますが、ソースアプライアンスがこれらのネットワークに接続されている場合は、管理ネットワークまたはクライアントネットワークも使用できます。StorageGRID ネットワークのパフォーマンスやデータの可用性を低下させることなく、最高のデータ転送パフォーマンスを提供するトラフィックのクローニングに使用するネットワークを選択してください。

交換用アプライアンスを設置するときは、 StorageGRID 接続およびデータ転送用の一時的な IP アドレスを指定する必要があります。交換用アプライアンスは、交換するアプライアンスノードと同じネットワークの一部になるため、交換用アプライアンスでこれらの各ネットワークの一時的なIPアドレスを指定する必要があります。



== ターゲットアプライアンスの互換性

交換用アプライアンスは、交換するソースノードと同じタイプで、両方が同じ論理 StorageGRID サイトに属している必要があります。

* 交換用サービスアプライアンスは、交換する管理ノードまたはゲートウェイノードとは異なる場合があります。
+
** SG1000 サービスのターゲットアプライアンスに SG100 ソースノードアプライアンスをクローニングして、管理ノードまたはゲートウェイノードの機能を強化できます。
** SG1000 ソースノードアプライアンスを SG100 サービスターゲットアプライアンスにクローニングして、要件の厳しいアプリケーション用に SG1000 を再導入することができます。
+
たとえば、 SG1000 ソースノードアプライアンスを管理ノードとして使用していて、専用のロードバランシングノードとして使用する場合などです。

** SG1000 ソースノードアプライアンスを SG100 サービスターゲットアプライアンスに交換すると、ネットワークポートの最大速度が 100GbE から 25GbE に減ります。
** サービスアプライアンスのネットワークコネクタはそれぞれ異なります。アプライアンスのタイプを変更する場合は、ケーブルまたは SFP モジュールの交換が必要になることがあります。


* 交換用ストレージアプライアンスには、交換するストレージノードよりも大きな容量が必要です。
+
** ターゲットストレージアプライアンスのドライブ数がソースノードと同じである場合は、ターゲットアプライアンスのドライブの容量（TB）を増やす必要があります。
** ソースノードで使用したのと同じRAIDモードをターゲットノードで使用する場合は、 ストレージ効率に劣るRAIDモード（RAID 6からDDPへの切り替えなど）の場合は、ターゲットアプライアンスのドライブがソースアプライアンスのドライブよりも大きい（TB単位）必要があります。
** ソリッドステートドライブ（SSD）の設置により、ターゲットストレージアプライアンスに設置されている標準ドライブの数がソースノードのドライブの数よりも少ない場合は、ターゲットアプライアンスの標準ドライブの全体的なストレージ容量（TB） ソースストレージノード内のすべてのドライブの合計機能ドライブ容量を超える必要があります。
+
たとえば、60本のドライブを搭載したSG5760ソースストレージノードアプライアンスを58本の標準ドライブを搭載したSG6060ターゲットアプライアンスにクローニングする場合は、ストレージ容量を維持するために、クローニングの前に大容量のドライブをSG6060ターゲットアプライアンスにインストールする必要があります。（ターゲットアプライアンスのSSDを搭載した2つのドライブスロットは、アプライアンスのストレージ容量の合計には含まれません）。

+
ただし、60ドライブのSG5760ソースノードアプライアンスにSANtricity Dynamic Disk Pools DDP-8が設定されている場合は、58ドライブの同サイズのドライブを搭載したSG6060ターゲットアプライアンスにDDP-16を設定すると、ストレージ効率が向上するためにSG6060アプライアンスが有効なクローンターゲットになる可能性があります。

+
ソースアプライアンスノードの現在の RAID モードに関する情報は、 Grid Manager の * nodes * ページで確認できます。アプライアンスの [*Storage*] タブを選択します。



* ターゲットストレージアプライアンスのボリューム数は、ソースノードのボリューム数以上である必要があります。16個のオブジェクトストアボリューム（rangedb）を含むソースノードを、12個のオブジェクトストアボリュームを含むターゲットストレージアプライアンスにクローニングすることはできません。これは、ターゲットアプライアンスの容量がソースノードよりも大きい場合でも同様です。ほとんどのストレージアプライアンスにはオブジェクトストアボリュームが16個ありますが、オブジェクトストアボリュームが12個しかないSGF6112ストレージアプライアンスは除きます。




== クローニングされない情報

次のアプライアンス構成は、クローニング中に交換用アプライアンスに転送されません。交換用アプライアンスの初期セットアップ時に設定する必要があります。

* BMCインターフェイス
* ネットワークリンク
* ノード暗号化ステータス
* SANtricity システムマネージャ（ストレージノード用）
* RAID モード（ストレージノード用）




== クローニングの妨げとなる問題

クローニング中に次のいずれかの問題が発生すると、クローニングプロセスが停止し、エラーメッセージが生成されます。

* ネットワーク設定が正しくありません
* ソースとターゲットのアプライアンス間の接続が確立されていません
* ソースとターゲットのアプライアンスに互換性がない
* ストレージノードの場合は、容量の不十分な交換用アプライアンス


続行するには、クローニングのために各問題 を解決する必要があります。
