---
permalink: commonhardware/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: StorageGRID でアプライアンスノードをクローニングして、アプライアンスの設計や機能を強化することができます。クローニングを実行すると、既存のノードに関するすべての情報が新しいアプライアンスに転送され、ハードウェアのアップグレードプロセスを簡単に実行できます。また、アプライアンスの運用停止や拡張を行う代わりに、アプライアンスを交換することもできます。 
---
= StorageGRIDアプライアンスノードのクローン作成の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID でアプライアンスノードをクローニングして、アプライアンスの設計や機能を強化することができます。クローニングを実行すると、既存のノードに関するすべての情報が新しいアプライアンスに転送され、ハードウェアのアップグレードプロセスを簡単に実行できます。また、アプライアンスの運用停止や拡張を行う代わりに、アプライアンスを交換することもできます。

アプライアンスノードのクローニングを使用すると、グリッド内の既存のアプライアンスノード（ソース）を、同じ論理 StorageGRID サイトに含まれる互換性のあるアプライアンス（ターゲット）に簡単に置き換えることができます。このプロセスでは、すべてのデータが新しいアプライアンスに転送され、古いアプライアンスノードを交換するためにアプライアンスが稼働中になり、古いアプライアンスは設置前の状態になります。



== アプライアンスノードをクローニングする理由

アプライアンスノードは、次の処理が必要な場合にクローニングできます。

* 寿命が近づいているアプライアンスの交換
* 改善されたアプライアンステクノロジを活用するには、既存のノードをアップグレードしてください。
* StorageGRID システム内のストレージノードの数を変更することなく、グリッドのストレージ容量を拡張できます。
* RAID モードを DDP 8 から DDP 16 に変更する、 RAID 6 に変更するなどして、ストレージ効率を向上
* ノード暗号化を効率的に実装して、外部キー管理サーバ（ KMS ）を使用できるようにします。




== どの StorageGRID ネットワークが使用されていますか？

クローニングでは、 3 つの StorageGRID ネットワークのいずれかで、ソースノードからターゲットアプライアンスにデータが直接転送されます。グリッドネットワークは通常は使用されますが、ソースアプライアンスがこれらのネットワークに接続されている場合は、管理ネットワークまたはクライアントネットワークも使用できます。StorageGRID ネットワークのパフォーマンスやデータの可用性を低下させることなく、最高のデータ転送パフォーマンスを提供するトラフィックのクローニングに使用するネットワークを選択してください。

交換用アプライアンスを設置するときは、 StorageGRID 接続およびデータ転送用の一時的な IP アドレスを指定する必要があります。交換用アプライアンスは、交換するアプライアンスノードと同じネットワークの一部になるため、交換用アプライアンスでこれらの各ネットワークの一時的なIPアドレスを指定する必要があります。



== クローニングされない情報

次のアプライアンス構成は、クローニング中に交換用アプライアンスに転送されません。これらの設定は、交換用アプライアンスの初期セットアップ時に行う必要があります。

* BMCインターフェイス
* ネットワークリンク
* ノード暗号化ステータス
* SANtricity システムマネージャ（ストレージノード用）
* RAID モード（ストレージノード用）




== クローニングの妨げとなる問題

クローニング中に次のいずれかの問題が発生すると、クローニングプロセスが停止し、エラーメッセージが生成されます。

* ネットワーク設定が正しくありません
* ソースとターゲットのアプライアンス間の接続が確立されていません
* ソースとターゲットのアプライアンスに互換性がない
* ストレージノードの場合は、容量の不十分な交換用アプライアンス


続行するには、クローニングのために各問題 を解決する必要があります。



== ターゲットアプライアンスの互換性

交換用アプライアンスは、交換するソースノードと同じタイプで、両方が同じ論理 StorageGRID サイトに属している必要があります。

クローニングの前に、クローニングに関する一般的な考慮事項、特定のクローニング情報、および各アプライアンスタイプの制限事項を確認してください。



=== サービスアプライアンスのクローニングに関する一般的な考慮事項

* 交換用サービスアプライアンスは、交換する管理ノードまたはゲートウェイノードとは異なるモデルにすることができます。
* サービスアプライアンスのネットワークコネクタはそれぞれ異なります。アプライアンスのタイプを変更する場合は、ケーブルまたは SFP モジュールの交換が必要になることがあります。




=== ストレージアプライアンスのクローニングに関する一般的な考慮事項

* 交換用ストレージアプライアンスには、交換するストレージノードよりも大きな容量が必要です。
+
** ターゲットストレージアプライアンスのドライブ数がソースノードと同じである場合は、ターゲットアプライアンスのドライブの容量（TB）を増やす必要があります。
** ソースノードで使用したのと同じRAIDモードをターゲットノードで使用する場合は、 ストレージ効率に劣るRAIDモード（RAID 6からDDPへの切り替えなど）の場合は、ターゲットアプライアンスのドライブがソースアプライアンスのドライブよりも大きい（TB単位）必要があります。
** ターゲットストレージアプライアンス内のボリューム数は、ソースノード内のボリューム数以上でなければなりません。SGF6112には12個のボリュームがあり、SGF6212には13個のボリュームがあります。その他のストレージアプライアンスはすべて16個のボリュームがあります。
** ストレージアプライアンスのクローニングに関する一般的な考慮事項の例外は次のとおりです。
+
*** ソリッドステートドライブ（SSD）の設置により、ターゲットストレージアプライアンスに設置されている標準ドライブの数がソースノードのドライブの数よりも少ない場合は、ターゲットアプライアンスの標準ドライブの全体的なストレージ容量（TB） ソースストレージノード内のすべてのドライブの合計機能ドライブ容量を超える必要があります。
+
たとえば、60本のドライブを搭載したSG5760ソースストレージノードアプライアンスを58本の標準ドライブを搭載したSG6060ターゲットアプライアンスにクローニングする場合は、ストレージ容量を維持するために、クローニングの前に大容量のドライブをSG6060ターゲットアプライアンスにインストールする必要があります。（ターゲットアプライアンスのSSDを搭載した2つのドライブスロットは、アプライアンスのストレージ容量の合計には含まれません）。

+
ただし、60ドライブのSG5760ソースノードアプライアンスにSANtricity Dynamic Disk Pools DDP-8（DDP）が設定されている場合、58ドライブの同サイズのドライブを搭載したSG6060ターゲットアプライアンスにDDP-16を設定すると、ストレージ効率が向上するためにSG6060アプライアンスが有効なクローンターゲットになる可能性があります。

+
ソースアプライアンスノードの現在のRAIDモードに関する情報は、Grid Managerの*Nodes*ページで確認できます。アプライアンスの*Storage*タブを選択してください。

*** オブジェクトストアボリュームが16個（rangedb）あるソースノードを、オブジェクトストアボリュームが少ないターゲットストレージアプライアンスにクローンすることはできません。ターゲットアプライアンスの容量がソースノードよりも大きい場合でも同様です。








=== SG100アプライアンスのクローニング情報と制限事項

SG100ソースノードアプライアンスは、SG110、SG1000、またはSG1100サービスターゲットアプライアンスにクローニングできます。SG100をSG1000またはSG1100サービスターゲットアプライアンスにクローニングすると、管理ノードまたはゲートウェイノードの機能が向上します。



=== SG110アプライアンスのクローニング情報と制限事項

SG110ソースノードアプライアンスをSG1100サービスアプライアンスターゲットにクローニングすると、管理ノードまたはゲートウェイノードの機能を強化できます。

ノード暗号化なしの SG110 ソース ノード アプライアンスからノード暗号化ありの SG110 アプライアンス ターゲットへのノードのクローン作成はサポートされていません。



=== SG120アプライアンスのクローン作成に関する情報と制限事項

SG120ソースノードアプライアンスをSG1200サービスアプライアンスターゲットにクローニングすることで、管理ノードまたはゲートウェイノードの機能を向上させることができます。

ノード暗号化が有効になっていないSG120ソースノードアプライアンスから、ノード暗号化が有効になっているSG120ターゲットアプライアンスへのノードクローニングはサポートされていません。



=== SG1000アプライアンスのクローニング情報および制限事項

SG1000ソースノードアプライアンスをSG100、SG110、またはSG1100サービスターゲットアプライアンスにクローニングできます。

* SG1000をSG100またはSG110サービスターゲットアプライアンスにクローニングすると、要件の厳しいアプリケーション向けにSG1000を再導入できます。
* SG1000 ソースノードアプライアンスを SG100 サービスターゲットアプライアンスに交換すると、ネットワークポートの最大速度が 100GbE から 25GbE に減ります。




=== SG1100アプライアンスのクローニング情報と制限事項

SG1100ソースノードアプライアンスをSG110サービスターゲットアプライアンスにクローニングできます。

* SG1100をSG110サービスターゲットアプライアンスにクローニングすると、要件の厳しいアプリケーション向けにSG1100を再導入できます。たとえば、 SG1100 ソースノードアプライアンスを管理ノードとして使用していて、専用のロードバランシングノードとして使用する場合などです。
* SG1100ソースノードアプライアンスをSG110サービスターゲットアプライアンスに置き換えると、ネットワークポートの最大速度が100GbEから25GbEに短縮されます。


ノード暗号化なしの SG1100 ソース ノード アプライアンスからノード暗号化ありの SG1100 アプライアンス ターゲットへのノードのクローン作成はサポートされていません。



=== SG1200アプライアンスのクローン作成に関する情報と制限事項

SG1200ソースノードアプライアンスをSG120サービスターゲットアプライアンスにクローニングできます。

* SG1200をSG120サービスターゲットアプライアンスにクローンすることで、SG1200をより要求の厳しいアプリケーション向けに再展開できます。例えば、SG1200ソースノードアプライアンスを管理ノードとして使用している場合、それを専用のロードバランシングノードとして使用することができます。
* SG1200ソースノードアプライアンスをSG120サービスターゲットアプライアンスに交換すると、ネットワークポートの最大速度が100-GbEから25-GbEに低下します。


ノード暗号化が有効になっていないSG1200ソースノードアプライアンスから、ノード暗号化が有効になっているSG1200ターゲットアプライアンスへのノードクローニングはサポートされていません。



=== SG5712アプライアンスのクローニング情報と制限事項

DDPが設定されたSG5712ソースノードアプライアンスは、SG5812ストレージターゲットアプライアンスにクローニングできます。



=== SG5760アプライアンスのクローニング情報と制限事項

* DDP16が設定されたSG5760ソースノードアプライアンスを、DDP16が設定されたSG5860ストレージターゲットアプライアンスにクローニングできます。
* DDPが設定されたソースノードのSG5760アプライアンスは、DDPが設定されたSG5860ストレージターゲットアプライアンスにクローニングできます。
* DDPまたはDDP-16で構成されたSG5760ソースノードアプライアンスは、同じRAIDモードのSG6160またはSG6260ストレージターゲットアプライアンスにクローンすることはできません。




=== SG5812アプライアンスのクローニング情報と制限事項

SG5812アプライアンスをソースまたはターゲットとして正常にクローニングできます。



=== SG5860アプライアンスのクローニング情報と制限事項

SG5860アプライアンスをソースまたはターゲットとして正常にクローニングできますが、いくつかの制限（アプライアンスのクローニング情報およびソースごとの制限事項に記載）があります。



=== SG6060アプライアンスのクローニング情報と制限事項

* DDPまたはDDP16で構成されたソースノードのSG6060アプライアンスは、RAIDモードが一致するSG5860ストレージターゲットアプライアンスにクローニングできます。
* ドライブサイズとRAIDモードが同じであれば、拡張シェルフのないSG6060ソースノードアプライアンスを、拡張シェルフのないSG6160またはSG6260ストレージターゲットアプライアンスにクローンできます。
* 拡張シェルフの数、ドライブサイズ、RAIDモードが同じであっても、SG6060ソースノードアプライアンス（拡張シェルフの数に関わらず）をSG6160またはSG6260ストレージターゲットアプライアンスにクローンすることは_できません_。




=== SGF6112アプライアンスのクローン情報と制限

ノード暗号化が有効になっていないSGF6112ソースノードアプライアンスから、ノード暗号化が有効になっているSGF6112またはSGF6212アプライアンスターゲットへのノードクローニングはサポートされていません。



=== SG6160およびSG6260アプライアンスのクローン作成に関する情報と制限事項

SG6160アプライアンスをソースまたはターゲットとして正常にクローニングできますが、いくつかの制限事項（アプライアンスのクローニング情報およびソースごとの制限事項に記載）があります。
