---
permalink: commonhardware/locate-mac-address.html 
sidebar: sidebar 
keywords: storagegrid, mac, mac address 
summary: 場合によっては、アプライアンスの交換後にMACアドレス参照の更新が必要になることがあります。 
---
= MACアドレス参照を更新（SG100、SG1000、SGF6024、およびSG6060）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
場合によっては、アプライアンスの交換後にMACアドレス参照の更新が必要になることがあります。

.このタスクについて
交換するアプライアンスのいずれかのネットワークインターフェイスがDHCP用に設定されている場合は、交換用アプライアンスのMACアドレスを参照するために、DHCPサーバの永続的なDHCPリース割り当てを更新する必要があります。この更新により、交換用アプライアンスに想定されるIPアドレスが確実に割り当てられます。

.手順
. アプライアンス前面のラベルを確認します。ラベルには、アプライアンスのBMC管理ポートのMACアドレスが記載されています。
. 管理ネットワークポートの MAC アドレスを特定するには、ラベルに記載された 16 進数に * 2 * を追加する必要があります。
+
たとえば、ラベルに記載されている MAC アドレスの末尾が * 09 * の場合、管理ポートの MAC アドレスの末尾は * 0B * となります。ラベルに記載された MAC アドレスの末尾が * （ _y_） FF* の場合、管理ポートの MAC アドレスの末尾は * （ _y_+1 ） 01 * となります。

+
この計算を簡単に行うには、 Windows で Calculator を開き、 Programmer モードに設定して Hex を選択し、 MAC アドレスを入力してから、 *+2=* と入力します。

. 取り外したアプライアンスの DNS / ネットワークおよび IP アドレスを交換用アプライアンスの MAC アドレスと関連付けるよう、ネットワーク管理者に依頼します。
+

CAUTION: 交換用アプライアンスに電源を投入する前に、元のアプライアンスのすべての IP アドレスが更新されたことを確認する必要があります。そうしないと、アプライアンスのブート時に新しい DHCP IP アドレスが取得されて、 StorageGRID に再接続できなくなることがあります。この手順では、アプライアンスに接続されているすべての StorageGRID ネットワークを環境 接続します。

+

NOTE: 元のアプライアンスが静的 IP アドレスを使用していた場合は、取り外したアプライアンスの IP アドレスが自動的に新しいアプライアンスで使用されます。


